// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGene (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        numReps_dout,
        numReps_empty_n,
        numReps_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [2:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [2:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
input  [31:0] numReps_dout;
input   numReps_empty_n;
output   numReps_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_read;
reg out_V_V_write;
reg numReps_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln199_reg_835;
reg   [0:0] and_ln245_reg_870;
reg    out_V_V_blk_n;
reg   [0:0] icmp_ln215_reg_839;
reg    numReps_blk_n;
reg   [38:0] indvar_flatten_reg_197;
reg   [6:0] i_0_i_reg_208;
reg   [31:0] reg_286;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_predicate_op151_write_state4;
reg    ap_predicate_op154_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln196_fu_319_p2;
wire   [0:0] icmp_ln199_fu_355_p2;
wire   [0:0] and_ln245_fu_521_p2;
reg   [31:0] numReps_read_reg_816;
reg    ap_block_state1;
wire   [38:0] bound_fu_313_p2;
reg   [38:0] bound_reg_821;
wire    ap_CS_fsm_state2;
wire   [38:0] add_ln196_fu_324_p2;
wire   [0:0] icmp_ln215_fu_364_p2;
reg   [31:0] k_y_1_load_reg_843;
wire   [0:0] icmp_ln252_fu_268_p2;
reg   [0:0] icmp_ln252_reg_874;
wire   [0:0] icmp_ln205_fu_274_p2;
reg   [0:0] icmp_ln205_reg_879;
wire   [6:0] i_fu_624_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
wire   [3:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [2:0] inputBuf_0_V_q0;
reg   [3:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
wire   [3:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [2:0] inputBuf_1_V_q0;
reg   [3:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
wire   [63:0] zext_ln221_fu_400_p1;
wire   [63:0] zext_ln248_fu_654_p1;
wire   [63:0] zext_ln202_fu_699_p1;
reg   [31:0] read_block_2_fu_68;
wire   [31:0] select_ln197_fu_342_p3;
wire   [31:0] zext_ln252_fu_549_p1;
wire   [31:0] read_block_fu_607_p2;
reg   [31:0] ofm_y_1_i_fu_72;
wire   [31:0] select_ln236_1_fu_497_p3;
wire   [0:0] icmp_ln224_fu_412_p2;
wire   [0:0] icmp_ln227_fu_429_p2;
wire   [0:0] icmp_ln230_fu_443_p2;
wire   [0:0] icmp_ln233_fu_463_p2;
reg   [31:0] ofm_x_1_fu_76;
wire   [31:0] ofm_x_fu_457_p2;
reg   [31:0] k_y_1_fu_80;
wire   [31:0] k_y_fu_382_p2;
reg   [31:0] inp_1_fu_84;
wire   [31:0] select_ln236_fu_489_p3;
wire   [31:0] inp_fu_591_p2;
reg   [31:0] k_x_1_fu_88;
wire   [31:0] k_x_fu_423_p2;
reg   [31:0] count_simd_1_fu_92;
wire   [31:0] count_simd_fu_406_p2;
reg   [31:0] current_block_write_5_fu_96;
wire   [31:0] current_block_write_9_fu_687_p3;
wire   [31:0] current_block_write_6_fu_721_p3;
reg   [31:0] current_line_2_fu_100;
wire   [31:0] select_ln252_fu_533_p3;
wire   [31:0] grp_fu_262_p2;
reg   [31:0] counter_internal_blo_fu_104;
wire   [31:0] select_ln264_fu_578_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] trunc_ln321_1_fu_660_p1;
wire   [0:0] trunc_ln321_fu_705_p1;
wire   [31:0] bound_fu_313_p0;
wire   [0:0] icmp_ln197_fu_336_p2;
wire   [31:0] add_ln220_fu_388_p2;
wire   [31:0] current_line_in_bloc_fu_394_p2;
wire   [31:0] ofm_y_fu_477_p2;
wire   [0:0] icmp_ln236_fu_483_p2;
wire   [0:0] icmp_ln245_fu_515_p2;
wire   [3:0] trunc_ln197_fu_351_p1;
wire   [3:0] add_ln255_fu_527_p2;
wire   [3:0] read_block_3_fu_541_p3;
wire   [31:0] counter_internal_blo_3_fu_566_p2;
wire   [0:0] icmp_ln264_fu_572_p2;
wire   [6:0] add_ln197_fu_618_p2;
wire   [0:0] trunc_ln216_1_fu_635_p1;
wire   [0:0] trunc_ln216_fu_632_p1;
wire   [0:0] xor_ln221_fu_639_p2;
wire   [31:0] current_block_write_7_fu_667_p2;
wire   [0:0] icmp_ln257_fu_673_p2;
wire   [31:0] current_block_write_8_fu_679_p3;
wire   [31:0] current_block_write_fu_709_p2;
wire   [0:0] icmp_ln208_fu_715_p2;
wire    ap_CS_fsm_state5;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op63_load_state3;
reg    ap_enable_operation_63;
reg    ap_enable_state3_pp0_iter0_stage0;
reg    ap_predicate_op148_load_state4;
reg    ap_enable_operation_148;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op160_store_state4;
reg    ap_enable_operation_160;
reg    ap_predicate_op181_store_state4;
reg    ap_enable_operation_181;
reg    ap_predicate_op64_load_state3;
reg    ap_enable_operation_64;
reg    ap_predicate_op149_load_state4;
reg    ap_enable_operation_149;
reg    ap_predicate_op162_store_state4;
reg    ap_enable_operation_162;
reg    ap_predicate_op183_store_state4;
reg    ap_enable_operation_183;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [38:0] bound_fu_313_p00;
reg    ap_condition_337;
reg    ap_condition_51;
reg    ap_condition_348;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

ConvolutionInputGbkb #(
    .DataWidth( 3 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbkb #(
    .DataWidth( 3 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(in_V_V_dout)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln224_fu_412_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        count_simd_1_fu_92 <= count_simd_fu_406_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln227_fu_429_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln230_fu_443_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln233_fu_463_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln233_fu_463_p2 == 1'd1) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_1_fu_92 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counter_internal_blo_fu_104 <= select_ln264_fu_578_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln205_fu_274_p2 == 1'd1) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_104 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_reg_879 == 1'd1) & (icmp_ln199_reg_835 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_5_fu_96 <= current_block_write_6_fu_721_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_5_fu_96 <= current_block_write_9_fu_687_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_5_fu_96 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_fu_274_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_line_2_fu_100 <= grp_fu_262_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (1'd1 == and_ln245_fu_521_p2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_line_2_fu_100 <= select_ln252_fu_533_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln205_fu_274_p2 == 1'd1) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_2_fu_100 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_i_reg_208 <= i_fu_624_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_0_i_reg_208 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_197 <= add_ln196_fu_324_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_reg_197 <= 39'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_1_fu_84 <= inp_fu_591_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln233_fu_463_p2 == 1'd1) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_1_fu_84 <= select_ln236_fu_489_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_1_fu_84 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln227_fu_429_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_x_1_fu_88 <= k_x_fu_423_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln230_fu_443_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln233_fu_463_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln233_fu_463_p2 == 1'd1) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_1_fu_88 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln230_fu_443_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_y_1_fu_80 <= k_y_fu_382_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_1_fu_80 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln233_fu_463_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofm_x_1_fu_76 <= ofm_x_fu_457_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln233_fu_463_p2 == 1'd1) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_1_fu_76 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln233_fu_463_p2 == 1'd1) & (icmp_ln230_fu_443_p2 == 1'd1) & (icmp_ln227_fu_429_p2 == 1'd1) & (icmp_ln224_fu_412_p2 == 1'd1) & (icmp_ln215_fu_364_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofm_y_1_i_fu_72 <= select_ln236_1_fu_497_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_i_fu_72 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln205_fu_274_p2 == 1'd1) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_2_fu_68 <= read_block_fu_607_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (1'd1 == and_ln245_fu_521_p2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_2_fu_68 <= zext_ln252_fu_549_p1;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_fu_274_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln245_fu_521_p2) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        read_block_2_fu_68 <= select_ln197_fu_342_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_2_fu_68 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln245_reg_870 <= and_ln245_fu_521_p2;
        icmp_ln215_reg_839 <= icmp_ln215_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_821[38 : 1] <= bound_fu_313_p2[38 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln199_reg_835 <= icmp_ln199_fu_355_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln205_reg_879 <= icmp_ln205_fu_274_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (1'd1 == and_ln245_fu_521_p2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln252_reg_874 <= icmp_ln252_fu_268_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln215_fu_364_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_y_1_load_reg_843 <= k_y_1_fu_80;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read_reg_816 <= numReps_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln199_fu_355_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (1'd1 == and_ln245_fu_521_p2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_286 <= current_line_2_fu_100;
    end
end

always @ (*) begin
    if ((icmp_ln196_fu_319_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_reg_835 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op154_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_reg_835 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_51)) begin
        if (((trunc_ln321_fu_705_p1 == 1'd0) & (icmp_ln199_reg_835 == 1'd1))) begin
            inputBuf_0_V_address1 = zext_ln202_fu_699_p1;
        end else if ((1'b1 == ap_condition_337)) begin
            inputBuf_0_V_address1 = zext_ln248_fu_654_p1;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_1_fu_660_p1 == 1'd0) & (1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_fu_705_p1 == 1'd0) & (icmp_ln199_reg_835 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_1_fu_660_p1 == 1'd0) & (1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_fu_705_p1 == 1'd0) & (icmp_ln199_reg_835 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_51)) begin
        if (((trunc_ln321_fu_705_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd1))) begin
            inputBuf_1_V_address1 = zext_ln202_fu_699_p1;
        end else if ((1'b1 == ap_condition_348)) begin
            inputBuf_1_V_address1 = zext_ln248_fu_654_p1;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_reg_870) & (trunc_ln321_1_fu_660_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_fu_705_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_reg_870) & (trunc_ln321_1_fu_660_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_fu_705_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_blk_n = numReps_empty_n;
    end else begin
        numReps_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read = 1'b1;
    end else begin
        numReps_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_839 == 1'd1) & (icmp_ln199_reg_835 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op151_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln196_fu_319_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln196_fu_319_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln196_fu_324_p2 = (indvar_flatten_reg_197 + 39'd1);

assign add_ln197_fu_618_p2 = (i_0_i_reg_208 + 7'd1);

assign add_ln220_fu_388_p2 = (ofm_x_1_fu_76 + count_simd_1_fu_92);

assign add_ln255_fu_527_p2 = (trunc_ln197_fu_351_p1 + 4'd1);

assign and_ln245_fu_521_p2 = (icmp_ln245_fu_515_p2 & icmp_ln215_fu_364_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op154_read_state4 == 1'b1)) | ((out_V_V_full_n == 1'b0) & (ap_predicate_op151_write_state4 == 1'b1)) | ((icmp_ln199_reg_835 == 1'd1) & (in_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op154_read_state4 == 1'b1)) | ((out_V_V_full_n == 1'b0) & (ap_predicate_op151_write_state4 == 1'b1)) | ((icmp_ln199_reg_835 == 1'd1) & (in_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op154_read_state4 == 1'b1)) | ((out_V_V_full_n == 1'b0) & (ap_predicate_op151_write_state4 == 1'b1)) | ((icmp_ln199_reg_835 == 1'd1) & (in_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((in_V_V_empty_n == 1'b0) & (ap_predicate_op154_read_state4 == 1'b1)) | ((out_V_V_full_n == 1'b0) & (ap_predicate_op151_write_state4 == 1'b1)) | ((icmp_ln199_reg_835 == 1'd1) & (in_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_337 = ((trunc_ln321_1_fu_660_p1 == 1'd0) & (1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_condition_348 = ((1'd1 == and_ln245_reg_870) & (trunc_ln321_1_fu_660_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_condition_51 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_148 = (ap_predicate_op148_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_149 = (ap_predicate_op149_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_160 = (ap_predicate_op160_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_162 = (ap_predicate_op162_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_181 = (ap_predicate_op181_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_183 = (ap_predicate_op183_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_63 = (ap_predicate_op63_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_64 = (ap_predicate_op64_load_state3 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state3_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op148_load_state4 = ((icmp_ln215_reg_839 == 1'd1) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_predicate_op149_load_state4 = ((icmp_ln215_reg_839 == 1'd1) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_predicate_op151_write_state4 = ((icmp_ln215_reg_839 == 1'd1) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_predicate_op154_read_state4 = ((1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_predicate_op160_store_state4 = ((trunc_ln321_1_fu_660_p1 == 1'd0) & (1'd1 == and_ln245_reg_870) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_predicate_op162_store_state4 = ((1'd1 == and_ln245_reg_870) & (trunc_ln321_1_fu_660_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd0));
end

always @ (*) begin
    ap_predicate_op181_store_state4 = ((trunc_ln321_fu_705_p1 == 1'd0) & (icmp_ln199_reg_835 == 1'd1));
end

always @ (*) begin
    ap_predicate_op183_store_state4 = ((trunc_ln321_fu_705_p1 == 1'd1) & (icmp_ln199_reg_835 == 1'd1));
end

always @ (*) begin
    ap_predicate_op63_load_state3 = ((icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln215_fu_364_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op64_load_state3 = ((icmp_ln199_fu_355_p2 == 1'd0) & (icmp_ln196_fu_319_p2 == 1'd0) & (icmp_ln215_fu_364_p2 == 1'd1));
end

assign bound_fu_313_p0 = bound_fu_313_p00;

assign bound_fu_313_p00 = numReps_read_reg_816;

assign bound_fu_313_p2 = (bound_fu_313_p0 * $signed('h6E));

assign count_simd_fu_406_p2 = (32'd1 + count_simd_1_fu_92);

assign counter_internal_blo_3_fu_566_p2 = (counter_internal_blo_fu_104 + 32'd1);

assign current_block_write_6_fu_721_p3 = ((icmp_ln208_fu_715_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_fu_709_p2);

assign current_block_write_7_fu_667_p2 = (current_block_write_5_fu_96 + 32'd1);

assign current_block_write_8_fu_679_p3 = ((icmp_ln257_fu_673_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_7_fu_667_p2);

assign current_block_write_9_fu_687_p3 = ((icmp_ln252_reg_874[0:0] === 1'b1) ? current_block_write_8_fu_679_p3 : current_block_write_5_fu_96);

assign current_block_write_fu_709_p2 = (current_block_write_5_fu_96 + 32'd1);

assign current_line_in_bloc_fu_394_p2 = (add_ln220_fu_388_p2 + k_x_1_fu_88);

assign grp_fu_262_p2 = (current_line_2_fu_100 + 32'd1);

assign i_fu_624_p3 = ((icmp_ln197_fu_336_p2[0:0] === 1'b1) ? 7'd1 : add_ln197_fu_618_p2);

assign icmp_ln196_fu_319_p2 = ((indvar_flatten_reg_197 == bound_reg_821) ? 1'b1 : 1'b0);

assign icmp_ln197_fu_336_p2 = ((i_0_i_reg_208 == 7'd110) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_355_p2 = ((inp_1_fu_84 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_274_p2 = ((grp_fu_262_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_715_p2 = ((current_block_write_fu_709_p2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_364_p2 = ((counter_internal_blo_fu_104 < 32'd9) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_412_p2 = ((count_simd_1_fu_92 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_429_p2 = ((k_x_1_fu_88 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_443_p2 = ((k_y_1_fu_80 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_463_p2 = ((ofm_x_fu_457_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln236_fu_483_p2 = ((ofm_y_fu_477_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_515_p2 = ((select_ln197_fu_342_p3 < 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_268_p2 = ((grp_fu_262_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_673_p2 = ((current_block_write_7_fu_667_p2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln264_fu_572_p2 = ((counter_internal_blo_3_fu_566_p2 == 32'd9) ? 1'b1 : 1'b0);

assign inp_fu_591_p2 = (inp_1_fu_84 + 32'd1);

assign inputBuf_0_V_address0 = zext_ln221_fu_400_p1;

assign inputBuf_1_V_address0 = zext_ln221_fu_400_p1;

assign k_x_fu_423_p2 = (k_x_1_fu_88 + 32'd1);

assign k_y_fu_382_p2 = (32'd1 + k_y_1_fu_80);

assign ofm_x_fu_457_p2 = (ofm_x_1_fu_76 + 32'd1);

assign ofm_y_fu_477_p2 = (ofm_y_1_i_fu_72 + 32'd1);

assign out_V_V_din = ((xor_ln221_fu_639_p2[0:0] === 1'b1) ? inputBuf_0_V_q0 : inputBuf_1_V_q0);

assign read_block_3_fu_541_p3 = ((icmp_ln252_fu_268_p2[0:0] === 1'b1) ? add_ln255_fu_527_p2 : trunc_ln197_fu_351_p1);

assign read_block_fu_607_p2 = (select_ln197_fu_342_p3 + 32'd1);

assign select_ln197_fu_342_p3 = ((icmp_ln197_fu_336_p2[0:0] === 1'b1) ? 32'd0 : read_block_2_fu_68);

assign select_ln236_1_fu_497_p3 = ((icmp_ln236_fu_483_p2[0:0] === 1'b1) ? 32'd0 : ofm_y_fu_477_p2);

assign select_ln236_fu_489_p3 = ((icmp_ln236_fu_483_p2[0:0] === 1'b1) ? 32'd0 : inp_1_fu_84);

assign select_ln252_fu_533_p3 = ((icmp_ln252_fu_268_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_262_p2);

assign select_ln264_fu_578_p3 = ((icmp_ln264_fu_572_p2[0:0] === 1'b1) ? 32'd0 : counter_internal_blo_3_fu_566_p2);

assign trunc_ln197_fu_351_p1 = select_ln197_fu_342_p3[3:0];

assign trunc_ln216_1_fu_635_p1 = current_block_write_5_fu_96[0:0];

assign trunc_ln216_fu_632_p1 = k_y_1_load_reg_843[0:0];

assign trunc_ln321_1_fu_660_p1 = current_block_write_5_fu_96[0:0];

assign trunc_ln321_fu_705_p1 = current_block_write_5_fu_96[0:0];

assign xor_ln221_fu_639_p2 = (trunc_ln216_fu_632_p1 ^ trunc_ln216_1_fu_635_p1);

assign zext_ln202_fu_699_p1 = reg_286;

assign zext_ln221_fu_400_p1 = current_line_in_bloc_fu_394_p2;

assign zext_ln248_fu_654_p1 = reg_286;

assign zext_ln252_fu_549_p1 = read_block_3_fu_541_p3;

always @ (posedge ap_clk) begin
    bound_reg_821[0] <= 1'b0;
end

endmodule //ConvolutionInputGene
