#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in_0", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("in_1", 1, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("in_2", 1, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("in_3", 1, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("in_4", 1, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("in_5", 1, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("in_6", 1, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("in_7", 1, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("out_0", 1, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("out_0_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("out_1", 1, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("out_1_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("out_2", 1, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("out_2_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("out_3", 1, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("out_3_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "fc_finn_top";
