// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ConvolutionInputGene.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ConvolutionInputGene::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ConvolutionInputGene::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> ConvolutionInputGene::ap_ST_fsm_state1 = "1";
const sc_lv<4> ConvolutionInputGene::ap_ST_fsm_state2 = "10";
const sc_lv<4> ConvolutionInputGene::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> ConvolutionInputGene::ap_ST_fsm_state5 = "1000";
const sc_lv<32> ConvolutionInputGene::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool ConvolutionInputGene::ap_const_boolean_1 = true;
const sc_lv<32> ConvolutionInputGene::ap_const_lv32_2 = "10";
const bool ConvolutionInputGene::ap_const_boolean_0 = false;
const sc_lv<1> ConvolutionInputGene::ap_const_lv1_1 = "1";
const sc_lv<1> ConvolutionInputGene::ap_const_lv1_0 = "0";
const sc_lv<32> ConvolutionInputGene::ap_const_lv32_1 = "1";
const sc_lv<39> ConvolutionInputGene::ap_const_lv39_0 = "000000000000000000000000000000000000000";
const sc_lv<7> ConvolutionInputGene::ap_const_lv7_0 = "0000000";
const sc_lv<32> ConvolutionInputGene::ap_const_lv32_A = "1010";
const sc_lv<39> ConvolutionInputGene::ap_const_lv39_6E = "1101110";
const sc_lv<39> ConvolutionInputGene::ap_const_lv39_1 = "1";
const sc_lv<7> ConvolutionInputGene::ap_const_lv7_6E = "1101110";
const sc_lv<32> ConvolutionInputGene::ap_const_lv32_9 = "1001";
const sc_lv<4> ConvolutionInputGene::ap_const_lv4_1 = "1";
const sc_lv<7> ConvolutionInputGene::ap_const_lv7_1 = "1";
const sc_lv<32> ConvolutionInputGene::ap_const_lv32_3 = "11";

ConvolutionInputGene::ConvolutionInputGene(sc_module_name name) : sc_module(name), mVcdFile(0) {
    inputBuf_0_V_U = new ConvolutionInputGbkb("inputBuf_0_V_U");
    inputBuf_0_V_U->clk(ap_clk);
    inputBuf_0_V_U->reset(ap_rst);
    inputBuf_0_V_U->address0(inputBuf_0_V_address0);
    inputBuf_0_V_U->ce0(inputBuf_0_V_ce0);
    inputBuf_0_V_U->q0(inputBuf_0_V_q0);
    inputBuf_0_V_U->address1(inputBuf_0_V_address1);
    inputBuf_0_V_U->ce1(inputBuf_0_V_ce1);
    inputBuf_0_V_U->we1(inputBuf_0_V_we1);
    inputBuf_0_V_U->d1(in_V_V_dout);
    inputBuf_1_V_U = new ConvolutionInputGbkb("inputBuf_1_V_U");
    inputBuf_1_V_U->clk(ap_clk);
    inputBuf_1_V_U->reset(ap_rst);
    inputBuf_1_V_U->address0(inputBuf_1_V_address0);
    inputBuf_1_V_U->ce0(inputBuf_1_V_ce0);
    inputBuf_1_V_U->q0(inputBuf_1_V_q0);
    inputBuf_1_V_U->address1(inputBuf_1_V_address1);
    inputBuf_1_V_U->ce1(inputBuf_1_V_ce1);
    inputBuf_1_V_U->we1(inputBuf_1_V_we1);
    inputBuf_1_V_U->d1(in_V_V_dout);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln196_fu_324_p2);
    sensitive << ( indvar_flatten_reg_197 );

    SC_METHOD(thread_add_ln197_fu_618_p2);
    sensitive << ( i_0_i_reg_208 );

    SC_METHOD(thread_add_ln220_fu_388_p2);
    sensitive << ( ofm_x_1_fu_76 );
    sensitive << ( count_simd_1_fu_92 );

    SC_METHOD(thread_add_ln255_fu_527_p2);
    sensitive << ( trunc_ln197_fu_351_p1 );

    SC_METHOD(thread_and_ln245_fu_521_p2);
    sensitive << ( icmp_ln215_fu_364_p2 );
    sensitive << ( icmp_ln245_fu_515_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( ap_predicate_op151_write_state4 );
    sensitive << ( ap_predicate_op154_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( ap_predicate_op151_write_state4 );
    sensitive << ( ap_predicate_op154_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( ap_predicate_op151_write_state4 );
    sensitive << ( ap_predicate_op154_read_state4 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( numReps_empty_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( ap_predicate_op151_write_state4 );
    sensitive << ( ap_predicate_op154_read_state4 );

    SC_METHOD(thread_ap_condition_337);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );

    SC_METHOD(thread_ap_condition_348);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );

    SC_METHOD(thread_ap_condition_51);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln196_fu_319_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_enable_operation_148);
    sensitive << ( ap_predicate_op148_load_state4 );

    SC_METHOD(thread_ap_enable_operation_149);
    sensitive << ( ap_predicate_op149_load_state4 );

    SC_METHOD(thread_ap_enable_operation_160);
    sensitive << ( ap_predicate_op160_store_state4 );

    SC_METHOD(thread_ap_enable_operation_162);
    sensitive << ( ap_predicate_op162_store_state4 );

    SC_METHOD(thread_ap_enable_operation_181);
    sensitive << ( ap_predicate_op181_store_state4 );

    SC_METHOD(thread_ap_enable_operation_183);
    sensitive << ( ap_predicate_op183_store_state4 );

    SC_METHOD(thread_ap_enable_operation_63);
    sensitive << ( ap_predicate_op63_load_state3 );

    SC_METHOD(thread_ap_enable_operation_64);
    sensitive << ( ap_predicate_op64_load_state3 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_state3_pp0_iter0_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_enable_state4_pp0_iter1_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_predicate_op148_load_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( icmp_ln215_reg_839 );

    SC_METHOD(thread_ap_predicate_op149_load_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( icmp_ln215_reg_839 );

    SC_METHOD(thread_ap_predicate_op151_write_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( icmp_ln215_reg_839 );

    SC_METHOD(thread_ap_predicate_op154_read_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );

    SC_METHOD(thread_ap_predicate_op160_store_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );

    SC_METHOD(thread_ap_predicate_op162_store_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );

    SC_METHOD(thread_ap_predicate_op181_store_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( trunc_ln321_fu_705_p1 );

    SC_METHOD(thread_ap_predicate_op183_store_state4);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( trunc_ln321_fu_705_p1 );

    SC_METHOD(thread_ap_predicate_op63_load_state3);
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );

    SC_METHOD(thread_ap_predicate_op64_load_state3);
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_bound_fu_313_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( bound_fu_313_p00 );

    SC_METHOD(thread_bound_fu_313_p00);
    sensitive << ( numReps_read_reg_816 );

    SC_METHOD(thread_bound_fu_313_p2);
    sensitive << ( bound_fu_313_p0 );

    SC_METHOD(thread_count_simd_fu_406_p2);
    sensitive << ( count_simd_1_fu_92 );

    SC_METHOD(thread_counter_internal_blo_3_fu_566_p2);
    sensitive << ( counter_internal_blo_fu_104 );

    SC_METHOD(thread_current_block_write_6_fu_721_p3);
    sensitive << ( current_block_write_fu_709_p2 );
    sensitive << ( icmp_ln208_fu_715_p2 );

    SC_METHOD(thread_current_block_write_7_fu_667_p2);
    sensitive << ( current_block_write_5_fu_96 );

    SC_METHOD(thread_current_block_write_8_fu_679_p3);
    sensitive << ( current_block_write_7_fu_667_p2 );
    sensitive << ( icmp_ln257_fu_673_p2 );

    SC_METHOD(thread_current_block_write_9_fu_687_p3);
    sensitive << ( icmp_ln252_reg_874 );
    sensitive << ( current_block_write_5_fu_96 );
    sensitive << ( current_block_write_8_fu_679_p3 );

    SC_METHOD(thread_current_block_write_fu_709_p2);
    sensitive << ( current_block_write_5_fu_96 );

    SC_METHOD(thread_current_line_in_bloc_fu_394_p2);
    sensitive << ( k_x_1_fu_88 );
    sensitive << ( add_ln220_fu_388_p2 );

    SC_METHOD(thread_grp_fu_262_p2);
    sensitive << ( current_line_2_fu_100 );

    SC_METHOD(thread_i_fu_624_p3);
    sensitive << ( icmp_ln197_fu_336_p2 );
    sensitive << ( add_ln197_fu_618_p2 );

    SC_METHOD(thread_icmp_ln196_fu_319_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_197 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( bound_reg_821 );

    SC_METHOD(thread_icmp_ln197_fu_336_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_0_i_reg_208 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );

    SC_METHOD(thread_icmp_ln199_fu_355_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( inp_1_fu_84 );

    SC_METHOD(thread_icmp_ln205_fu_274_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( grp_fu_262_p2 );

    SC_METHOD(thread_icmp_ln208_fu_715_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln205_reg_879 );
    sensitive << ( current_block_write_fu_709_p2 );

    SC_METHOD(thread_icmp_ln215_fu_364_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( counter_internal_blo_fu_104 );

    SC_METHOD(thread_icmp_ln224_fu_412_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );
    sensitive << ( count_simd_1_fu_92 );

    SC_METHOD(thread_icmp_ln227_fu_429_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );
    sensitive << ( icmp_ln224_fu_412_p2 );
    sensitive << ( k_x_1_fu_88 );

    SC_METHOD(thread_icmp_ln230_fu_443_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );
    sensitive << ( icmp_ln224_fu_412_p2 );
    sensitive << ( icmp_ln227_fu_429_p2 );
    sensitive << ( k_y_1_fu_80 );

    SC_METHOD(thread_icmp_ln233_fu_463_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );
    sensitive << ( icmp_ln224_fu_412_p2 );
    sensitive << ( icmp_ln227_fu_429_p2 );
    sensitive << ( icmp_ln230_fu_443_p2 );
    sensitive << ( ofm_x_fu_457_p2 );

    SC_METHOD(thread_icmp_ln236_fu_483_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( icmp_ln215_fu_364_p2 );
    sensitive << ( icmp_ln224_fu_412_p2 );
    sensitive << ( icmp_ln227_fu_429_p2 );
    sensitive << ( icmp_ln230_fu_443_p2 );
    sensitive << ( icmp_ln233_fu_463_p2 );
    sensitive << ( ofm_y_fu_477_p2 );

    SC_METHOD(thread_icmp_ln245_fu_515_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( select_ln197_fu_342_p3 );

    SC_METHOD(thread_icmp_ln252_fu_268_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( and_ln245_fu_521_p2 );
    sensitive << ( grp_fu_262_p2 );

    SC_METHOD(thread_icmp_ln257_fu_673_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln252_reg_874 );
    sensitive << ( current_block_write_7_fu_667_p2 );

    SC_METHOD(thread_icmp_ln264_fu_572_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( icmp_ln199_fu_355_p2 );
    sensitive << ( counter_internal_blo_3_fu_566_p2 );

    SC_METHOD(thread_in_V_V_blk_n);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );

    SC_METHOD(thread_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( ap_predicate_op154_read_state4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_inp_fu_591_p2);
    sensitive << ( inp_1_fu_84 );

    SC_METHOD(thread_inputBuf_0_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln221_fu_400_p1 );

    SC_METHOD(thread_inputBuf_0_V_address1);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( zext_ln248_fu_654_p1 );
    sensitive << ( zext_ln202_fu_699_p1 );
    sensitive << ( trunc_ln321_fu_705_p1 );
    sensitive << ( ap_condition_337 );
    sensitive << ( ap_condition_51 );

    SC_METHOD(thread_inputBuf_0_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_inputBuf_0_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );
    sensitive << ( trunc_ln321_fu_705_p1 );

    SC_METHOD(thread_inputBuf_0_V_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );
    sensitive << ( trunc_ln321_fu_705_p1 );

    SC_METHOD(thread_inputBuf_1_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln221_fu_400_p1 );

    SC_METHOD(thread_inputBuf_1_V_address1);
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( zext_ln248_fu_654_p1 );
    sensitive << ( zext_ln202_fu_699_p1 );
    sensitive << ( trunc_ln321_fu_705_p1 );
    sensitive << ( ap_condition_51 );
    sensitive << ( ap_condition_348 );

    SC_METHOD(thread_inputBuf_1_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_inputBuf_1_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );
    sensitive << ( trunc_ln321_fu_705_p1 );

    SC_METHOD(thread_inputBuf_1_V_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( and_ln245_reg_870 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln321_1_fu_660_p1 );
    sensitive << ( trunc_ln321_fu_705_p1 );

    SC_METHOD(thread_k_x_fu_423_p2);
    sensitive << ( k_x_1_fu_88 );

    SC_METHOD(thread_k_y_fu_382_p2);
    sensitive << ( k_y_1_fu_80 );

    SC_METHOD(thread_numReps_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );

    SC_METHOD(thread_numReps_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );

    SC_METHOD(thread_ofm_x_fu_457_p2);
    sensitive << ( ofm_x_1_fu_76 );

    SC_METHOD(thread_ofm_y_fu_477_p2);
    sensitive << ( ofm_y_1_i_fu_72 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln199_reg_835 );
    sensitive << ( icmp_ln215_reg_839 );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op151_write_state4 );
    sensitive << ( inputBuf_0_V_q0 );
    sensitive << ( inputBuf_1_V_q0 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( xor_ln221_fu_639_p2 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op151_write_state4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_read_block_3_fu_541_p3);
    sensitive << ( icmp_ln252_fu_268_p2 );
    sensitive << ( trunc_ln197_fu_351_p1 );
    sensitive << ( add_ln255_fu_527_p2 );

    SC_METHOD(thread_read_block_fu_607_p2);
    sensitive << ( select_ln197_fu_342_p3 );

    SC_METHOD(thread_select_ln197_fu_342_p3);
    sensitive << ( read_block_2_fu_68 );
    sensitive << ( icmp_ln197_fu_336_p2 );

    SC_METHOD(thread_select_ln236_1_fu_497_p3);
    sensitive << ( ofm_y_fu_477_p2 );
    sensitive << ( icmp_ln236_fu_483_p2 );

    SC_METHOD(thread_select_ln236_fu_489_p3);
    sensitive << ( inp_1_fu_84 );
    sensitive << ( icmp_ln236_fu_483_p2 );

    SC_METHOD(thread_select_ln252_fu_533_p3);
    sensitive << ( icmp_ln252_fu_268_p2 );
    sensitive << ( grp_fu_262_p2 );

    SC_METHOD(thread_select_ln264_fu_578_p3);
    sensitive << ( counter_internal_blo_3_fu_566_p2 );
    sensitive << ( icmp_ln264_fu_572_p2 );

    SC_METHOD(thread_trunc_ln197_fu_351_p1);
    sensitive << ( select_ln197_fu_342_p3 );

    SC_METHOD(thread_trunc_ln216_1_fu_635_p1);
    sensitive << ( current_block_write_5_fu_96 );

    SC_METHOD(thread_trunc_ln216_fu_632_p1);
    sensitive << ( k_y_1_load_reg_843 );

    SC_METHOD(thread_trunc_ln321_1_fu_660_p1);
    sensitive << ( current_block_write_5_fu_96 );

    SC_METHOD(thread_trunc_ln321_fu_705_p1);
    sensitive << ( current_block_write_5_fu_96 );

    SC_METHOD(thread_xor_ln221_fu_639_p2);
    sensitive << ( trunc_ln216_1_fu_635_p1 );
    sensitive << ( trunc_ln216_fu_632_p1 );

    SC_METHOD(thread_zext_ln202_fu_699_p1);
    sensitive << ( reg_286 );

    SC_METHOD(thread_zext_ln221_fu_400_p1);
    sensitive << ( current_line_in_bloc_fu_394_p2 );

    SC_METHOD(thread_zext_ln248_fu_654_p1);
    sensitive << ( reg_286 );

    SC_METHOD(thread_zext_ln252_fu_549_p1);
    sensitive << ( read_block_3_fu_541_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln196_fu_319_p2 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ConvolutionInputGene_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V_V_dout, "(port)in_V_V_dout");
    sc_trace(mVcdFile, in_V_V_empty_n, "(port)in_V_V_empty_n");
    sc_trace(mVcdFile, in_V_V_read, "(port)in_V_V_read");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
    sc_trace(mVcdFile, numReps_dout, "(port)numReps_dout");
    sc_trace(mVcdFile, numReps_empty_n, "(port)numReps_empty_n");
    sc_trace(mVcdFile, numReps_read, "(port)numReps_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_V_V_blk_n, "in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln199_reg_835, "icmp_ln199_reg_835");
    sc_trace(mVcdFile, and_ln245_reg_870, "and_ln245_reg_870");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, icmp_ln215_reg_839, "icmp_ln215_reg_839");
    sc_trace(mVcdFile, numReps_blk_n, "numReps_blk_n");
    sc_trace(mVcdFile, indvar_flatten_reg_197, "indvar_flatten_reg_197");
    sc_trace(mVcdFile, i_0_i_reg_208, "i_0_i_reg_208");
    sc_trace(mVcdFile, reg_286, "reg_286");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op151_write_state4, "ap_predicate_op151_write_state4");
    sc_trace(mVcdFile, ap_predicate_op154_read_state4, "ap_predicate_op154_read_state4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln196_fu_319_p2, "icmp_ln196_fu_319_p2");
    sc_trace(mVcdFile, icmp_ln199_fu_355_p2, "icmp_ln199_fu_355_p2");
    sc_trace(mVcdFile, and_ln245_fu_521_p2, "and_ln245_fu_521_p2");
    sc_trace(mVcdFile, numReps_read_reg_816, "numReps_read_reg_816");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, bound_fu_313_p2, "bound_fu_313_p2");
    sc_trace(mVcdFile, bound_reg_821, "bound_reg_821");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln196_fu_324_p2, "add_ln196_fu_324_p2");
    sc_trace(mVcdFile, icmp_ln215_fu_364_p2, "icmp_ln215_fu_364_p2");
    sc_trace(mVcdFile, k_y_1_load_reg_843, "k_y_1_load_reg_843");
    sc_trace(mVcdFile, icmp_ln252_fu_268_p2, "icmp_ln252_fu_268_p2");
    sc_trace(mVcdFile, icmp_ln252_reg_874, "icmp_ln252_reg_874");
    sc_trace(mVcdFile, icmp_ln205_fu_274_p2, "icmp_ln205_fu_274_p2");
    sc_trace(mVcdFile, icmp_ln205_reg_879, "icmp_ln205_reg_879");
    sc_trace(mVcdFile, i_fu_624_p3, "i_fu_624_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, inputBuf_0_V_address0, "inputBuf_0_V_address0");
    sc_trace(mVcdFile, inputBuf_0_V_ce0, "inputBuf_0_V_ce0");
    sc_trace(mVcdFile, inputBuf_0_V_q0, "inputBuf_0_V_q0");
    sc_trace(mVcdFile, inputBuf_0_V_address1, "inputBuf_0_V_address1");
    sc_trace(mVcdFile, inputBuf_0_V_ce1, "inputBuf_0_V_ce1");
    sc_trace(mVcdFile, inputBuf_0_V_we1, "inputBuf_0_V_we1");
    sc_trace(mVcdFile, inputBuf_1_V_address0, "inputBuf_1_V_address0");
    sc_trace(mVcdFile, inputBuf_1_V_ce0, "inputBuf_1_V_ce0");
    sc_trace(mVcdFile, inputBuf_1_V_q0, "inputBuf_1_V_q0");
    sc_trace(mVcdFile, inputBuf_1_V_address1, "inputBuf_1_V_address1");
    sc_trace(mVcdFile, inputBuf_1_V_ce1, "inputBuf_1_V_ce1");
    sc_trace(mVcdFile, inputBuf_1_V_we1, "inputBuf_1_V_we1");
    sc_trace(mVcdFile, zext_ln221_fu_400_p1, "zext_ln221_fu_400_p1");
    sc_trace(mVcdFile, zext_ln248_fu_654_p1, "zext_ln248_fu_654_p1");
    sc_trace(mVcdFile, zext_ln202_fu_699_p1, "zext_ln202_fu_699_p1");
    sc_trace(mVcdFile, read_block_2_fu_68, "read_block_2_fu_68");
    sc_trace(mVcdFile, select_ln197_fu_342_p3, "select_ln197_fu_342_p3");
    sc_trace(mVcdFile, zext_ln252_fu_549_p1, "zext_ln252_fu_549_p1");
    sc_trace(mVcdFile, read_block_fu_607_p2, "read_block_fu_607_p2");
    sc_trace(mVcdFile, ofm_y_1_i_fu_72, "ofm_y_1_i_fu_72");
    sc_trace(mVcdFile, select_ln236_1_fu_497_p3, "select_ln236_1_fu_497_p3");
    sc_trace(mVcdFile, icmp_ln224_fu_412_p2, "icmp_ln224_fu_412_p2");
    sc_trace(mVcdFile, icmp_ln227_fu_429_p2, "icmp_ln227_fu_429_p2");
    sc_trace(mVcdFile, icmp_ln230_fu_443_p2, "icmp_ln230_fu_443_p2");
    sc_trace(mVcdFile, icmp_ln233_fu_463_p2, "icmp_ln233_fu_463_p2");
    sc_trace(mVcdFile, ofm_x_1_fu_76, "ofm_x_1_fu_76");
    sc_trace(mVcdFile, ofm_x_fu_457_p2, "ofm_x_fu_457_p2");
    sc_trace(mVcdFile, k_y_1_fu_80, "k_y_1_fu_80");
    sc_trace(mVcdFile, k_y_fu_382_p2, "k_y_fu_382_p2");
    sc_trace(mVcdFile, inp_1_fu_84, "inp_1_fu_84");
    sc_trace(mVcdFile, select_ln236_fu_489_p3, "select_ln236_fu_489_p3");
    sc_trace(mVcdFile, inp_fu_591_p2, "inp_fu_591_p2");
    sc_trace(mVcdFile, k_x_1_fu_88, "k_x_1_fu_88");
    sc_trace(mVcdFile, k_x_fu_423_p2, "k_x_fu_423_p2");
    sc_trace(mVcdFile, count_simd_1_fu_92, "count_simd_1_fu_92");
    sc_trace(mVcdFile, count_simd_fu_406_p2, "count_simd_fu_406_p2");
    sc_trace(mVcdFile, current_block_write_5_fu_96, "current_block_write_5_fu_96");
    sc_trace(mVcdFile, current_block_write_9_fu_687_p3, "current_block_write_9_fu_687_p3");
    sc_trace(mVcdFile, current_block_write_6_fu_721_p3, "current_block_write_6_fu_721_p3");
    sc_trace(mVcdFile, current_line_2_fu_100, "current_line_2_fu_100");
    sc_trace(mVcdFile, select_ln252_fu_533_p3, "select_ln252_fu_533_p3");
    sc_trace(mVcdFile, grp_fu_262_p2, "grp_fu_262_p2");
    sc_trace(mVcdFile, counter_internal_blo_fu_104, "counter_internal_blo_fu_104");
    sc_trace(mVcdFile, select_ln264_fu_578_p3, "select_ln264_fu_578_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, trunc_ln321_1_fu_660_p1, "trunc_ln321_1_fu_660_p1");
    sc_trace(mVcdFile, trunc_ln321_fu_705_p1, "trunc_ln321_fu_705_p1");
    sc_trace(mVcdFile, bound_fu_313_p0, "bound_fu_313_p0");
    sc_trace(mVcdFile, icmp_ln197_fu_336_p2, "icmp_ln197_fu_336_p2");
    sc_trace(mVcdFile, add_ln220_fu_388_p2, "add_ln220_fu_388_p2");
    sc_trace(mVcdFile, current_line_in_bloc_fu_394_p2, "current_line_in_bloc_fu_394_p2");
    sc_trace(mVcdFile, ofm_y_fu_477_p2, "ofm_y_fu_477_p2");
    sc_trace(mVcdFile, icmp_ln236_fu_483_p2, "icmp_ln236_fu_483_p2");
    sc_trace(mVcdFile, icmp_ln245_fu_515_p2, "icmp_ln245_fu_515_p2");
    sc_trace(mVcdFile, trunc_ln197_fu_351_p1, "trunc_ln197_fu_351_p1");
    sc_trace(mVcdFile, add_ln255_fu_527_p2, "add_ln255_fu_527_p2");
    sc_trace(mVcdFile, read_block_3_fu_541_p3, "read_block_3_fu_541_p3");
    sc_trace(mVcdFile, counter_internal_blo_3_fu_566_p2, "counter_internal_blo_3_fu_566_p2");
    sc_trace(mVcdFile, icmp_ln264_fu_572_p2, "icmp_ln264_fu_572_p2");
    sc_trace(mVcdFile, add_ln197_fu_618_p2, "add_ln197_fu_618_p2");
    sc_trace(mVcdFile, trunc_ln216_1_fu_635_p1, "trunc_ln216_1_fu_635_p1");
    sc_trace(mVcdFile, trunc_ln216_fu_632_p1, "trunc_ln216_fu_632_p1");
    sc_trace(mVcdFile, xor_ln221_fu_639_p2, "xor_ln221_fu_639_p2");
    sc_trace(mVcdFile, current_block_write_7_fu_667_p2, "current_block_write_7_fu_667_p2");
    sc_trace(mVcdFile, icmp_ln257_fu_673_p2, "icmp_ln257_fu_673_p2");
    sc_trace(mVcdFile, current_block_write_8_fu_679_p3, "current_block_write_8_fu_679_p3");
    sc_trace(mVcdFile, current_block_write_fu_709_p2, "current_block_write_fu_709_p2");
    sc_trace(mVcdFile, icmp_ln208_fu_715_p2, "icmp_ln208_fu_715_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0, "ap_block_pp0");
    sc_trace(mVcdFile, ap_predicate_op63_load_state3, "ap_predicate_op63_load_state3");
    sc_trace(mVcdFile, ap_enable_operation_63, "ap_enable_operation_63");
    sc_trace(mVcdFile, ap_enable_state3_pp0_iter0_stage0, "ap_enable_state3_pp0_iter0_stage0");
    sc_trace(mVcdFile, ap_predicate_op148_load_state4, "ap_predicate_op148_load_state4");
    sc_trace(mVcdFile, ap_enable_operation_148, "ap_enable_operation_148");
    sc_trace(mVcdFile, ap_enable_state4_pp0_iter1_stage0, "ap_enable_state4_pp0_iter1_stage0");
    sc_trace(mVcdFile, ap_predicate_op160_store_state4, "ap_predicate_op160_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_160, "ap_enable_operation_160");
    sc_trace(mVcdFile, ap_predicate_op181_store_state4, "ap_predicate_op181_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_181, "ap_enable_operation_181");
    sc_trace(mVcdFile, ap_predicate_op64_load_state3, "ap_predicate_op64_load_state3");
    sc_trace(mVcdFile, ap_enable_operation_64, "ap_enable_operation_64");
    sc_trace(mVcdFile, ap_predicate_op149_load_state4, "ap_predicate_op149_load_state4");
    sc_trace(mVcdFile, ap_enable_operation_149, "ap_enable_operation_149");
    sc_trace(mVcdFile, ap_predicate_op162_store_state4, "ap_predicate_op162_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_162, "ap_enable_operation_162");
    sc_trace(mVcdFile, ap_predicate_op183_store_state4, "ap_predicate_op183_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_183, "ap_enable_operation_183");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, bound_fu_313_p00, "bound_fu_313_p00");
    sc_trace(mVcdFile, ap_condition_337, "ap_condition_337");
    sc_trace(mVcdFile, ap_condition_51, "ap_condition_51");
    sc_trace(mVcdFile, ap_condition_348, "ap_condition_348");
#endif

    }
}

ConvolutionInputGene::~ConvolutionInputGene() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete inputBuf_0_V_U;
    delete inputBuf_1_V_U;
}

void ConvolutionInputGene::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln224_fu_412_p2.read()))) {
        count_simd_1_fu_92 = count_simd_fu_406_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_463_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_fu_463_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln230_fu_443_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln227_fu_429_p2.read())))) {
        count_simd_1_fu_92 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()))) {
        counter_internal_blo_fu_104 = select_ln264_fu_578_p3.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln205_fu_274_p2.read())))) {
        counter_internal_blo_fu_104 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln205_reg_879.read()))) {
        current_block_write_5_fu_96 = current_block_write_6_fu_721_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        current_block_write_5_fu_96 = current_block_write_9_fu_687_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
        current_block_write_5_fu_96 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln205_fu_274_p2.read()))) {
        current_line_2_fu_100 = grp_fu_262_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_fu_521_p2.read()))) {
        current_line_2_fu_100 = select_ln252_fu_533_p3.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln205_fu_274_p2.read())))) {
        current_line_2_fu_100 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()))) {
        i_0_i_reg_208 = i_fu_624_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_0_i_reg_208 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()))) {
        indvar_flatten_reg_197 = add_ln196_fu_324_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        indvar_flatten_reg_197 = ap_const_lv39_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()))) {
        inp_1_fu_84 = inp_fu_591_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_463_p2.read()))) {
        inp_1_fu_84 = select_ln236_fu_489_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
        inp_1_fu_84 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln227_fu_429_p2.read()))) {
        k_x_1_fu_88 = k_x_fu_423_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_463_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_fu_463_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln230_fu_443_p2.read())))) {
        k_x_1_fu_88 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln230_fu_443_p2.read()))) {
        k_y_1_fu_80 = k_y_fu_382_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read())))) {
        k_y_1_fu_80 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_fu_463_p2.read()))) {
        ofm_x_1_fu_76 = ofm_x_fu_457_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_463_p2.read())))) {
        ofm_x_1_fu_76 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln224_fu_412_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_429_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln230_fu_443_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_463_p2.read()))) {
        ofm_y_1_i_fu_72 = select_ln236_1_fu_497_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
        ofm_y_1_i_fu_72 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln205_fu_274_p2.read()))) {
        read_block_2_fu_68 = read_block_fu_607_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_fu_521_p2.read()))) {
        read_block_2_fu_68 = zext_ln252_fu_549_p1.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln245_fu_521_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln205_fu_274_p2.read())))) {
        read_block_2_fu_68 = select_ln197_fu_342_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
        read_block_2_fu_68 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()))) {
        and_ln245_reg_870 = and_ln245_fu_521_p2.read();
        icmp_ln215_reg_839 = icmp_ln215_fu_364_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        bound_reg_821 = bound_fu_313_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()))) {
        icmp_ln199_reg_835 = icmp_ln199_fu_355_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read()))) {
        icmp_ln205_reg_879 = icmp_ln205_fu_274_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_fu_521_p2.read()))) {
        icmp_ln252_reg_874 = icmp_ln252_fu_268_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()))) {
        k_y_1_load_reg_843 = k_y_1_fu_80.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
        numReps_read_reg_816 = numReps_dout.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_fu_521_p2.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln199_fu_355_p2.read())))) {
        reg_286 = current_line_2_fu_100.read();
    }
}

void ConvolutionInputGene::thread_add_ln196_fu_324_p2() {
    add_ln196_fu_324_p2 = (!indvar_flatten_reg_197.read().is_01() || !ap_const_lv39_1.is_01())? sc_lv<39>(): (sc_biguint<39>(indvar_flatten_reg_197.read()) + sc_biguint<39>(ap_const_lv39_1));
}

void ConvolutionInputGene::thread_add_ln197_fu_618_p2() {
    add_ln197_fu_618_p2 = (!i_0_i_reg_208.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_0_i_reg_208.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void ConvolutionInputGene::thread_add_ln220_fu_388_p2() {
    add_ln220_fu_388_p2 = (!ofm_x_1_fu_76.read().is_01() || !count_simd_1_fu_92.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ofm_x_1_fu_76.read()) + sc_biguint<32>(count_simd_1_fu_92.read()));
}

void ConvolutionInputGene::thread_add_ln255_fu_527_p2() {
    add_ln255_fu_527_p2 = (!trunc_ln197_fu_351_p1.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(trunc_ln197_fu_351_p1.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void ConvolutionInputGene::thread_and_ln245_fu_521_p2() {
    and_ln245_fu_521_p2 = (icmp_ln215_fu_364_p2.read() & icmp_ln245_fu_515_p2.read());
}

void ConvolutionInputGene::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void ConvolutionInputGene::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ConvolutionInputGene::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ConvolutionInputGene::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void ConvolutionInputGene::thread_ap_block_pp0() {
    ap_block_pp0 = (esl_seteq<1,4,4>(ap_ST_fsm_pp0_stage0, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_pp0_stage0_subdone.read()));
}

void ConvolutionInputGene::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvolutionInputGene::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op151_write_state4.read())) || 
  (esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op154_read_state4.read())) || 
  (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()))));
}

void ConvolutionInputGene::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op151_write_state4.read())) || 
  (esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op154_read_state4.read())) || 
  (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()))));
}

void ConvolutionInputGene::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op151_write_state4.read())) || 
  (esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op154_read_state4.read())) || 
  (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()))));
}

void ConvolutionInputGene::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()));
}

void ConvolutionInputGene::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvolutionInputGene::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op151_write_state4.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op154_read_state4.read())) || (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())));
}

void ConvolutionInputGene::thread_ap_condition_337() {
    ap_condition_337 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_660_p1.read()));
}

void ConvolutionInputGene::thread_ap_condition_348() {
    ap_condition_348 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_660_p1.read()));
}

void ConvolutionInputGene::thread_ap_condition_51() {
    ap_condition_51 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0));
}

void ConvolutionInputGene::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln196_fu_319_p2.read())) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void ConvolutionInputGene::thread_ap_enable_operation_148() {
    ap_enable_operation_148 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op148_load_state4.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_149() {
    ap_enable_operation_149 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op149_load_state4.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_160() {
    ap_enable_operation_160 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op160_store_state4.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_162() {
    ap_enable_operation_162 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op162_store_state4.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_181() {
    ap_enable_operation_181 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op181_store_state4.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_183() {
    ap_enable_operation_183 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op183_store_state4.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_63() {
    ap_enable_operation_63 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op63_load_state3.read());
}

void ConvolutionInputGene::thread_ap_enable_operation_64() {
    ap_enable_operation_64 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op64_load_state3.read());
}

void ConvolutionInputGene::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void ConvolutionInputGene::thread_ap_enable_state3_pp0_iter0_stage0() {
    ap_enable_state3_pp0_iter0_stage0 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1));
}

void ConvolutionInputGene::thread_ap_enable_state4_pp0_iter1_stage0() {
    ap_enable_state4_pp0_iter1_stage0 = (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1));
}

void ConvolutionInputGene::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_ap_predicate_op148_load_state4() {
    ap_predicate_op148_load_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_reg_839.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op149_load_state4() {
    ap_predicate_op149_load_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_reg_839.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op151_write_state4() {
    ap_predicate_op151_write_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_reg_839.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op154_read_state4() {
    ap_predicate_op154_read_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op160_store_state4() {
    ap_predicate_op160_store_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_660_p1.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op162_store_state4() {
    ap_predicate_op162_store_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_660_p1.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op181_store_state4() {
    ap_predicate_op181_store_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_705_p1.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op183_store_state4() {
    ap_predicate_op183_store_state4 = (esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_705_p1.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op63_load_state3() {
    ap_predicate_op63_load_state3 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()));
}

void ConvolutionInputGene::thread_ap_predicate_op64_load_state3() {
    ap_predicate_op64_load_state3 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln196_fu_319_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_355_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_fu_364_p2.read()));
}

void ConvolutionInputGene::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_bound_fu_313_p0() {
    bound_fu_313_p0 =  (sc_lv<32>) (bound_fu_313_p00.read());
}

void ConvolutionInputGene::thread_bound_fu_313_p00() {
    bound_fu_313_p00 = esl_zext<39,32>(numReps_read_reg_816.read());
}

void ConvolutionInputGene::thread_bound_fu_313_p2() {
    bound_fu_313_p2 = (!bound_fu_313_p0.read().is_01() || !ap_const_lv39_6E.is_01())? sc_lv<39>(): sc_biguint<32>(bound_fu_313_p0.read()) * sc_biguint<39>(ap_const_lv39_6E);
}

void ConvolutionInputGene::thread_count_simd_fu_406_p2() {
    count_simd_fu_406_p2 = (!ap_const_lv32_1.is_01() || !count_simd_1_fu_92.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(count_simd_1_fu_92.read()));
}

void ConvolutionInputGene::thread_counter_internal_blo_3_fu_566_p2() {
    counter_internal_blo_3_fu_566_p2 = (!counter_internal_blo_fu_104.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(counter_internal_blo_fu_104.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_current_block_write_6_fu_721_p3() {
    current_block_write_6_fu_721_p3 = (!icmp_ln208_fu_715_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln208_fu_715_p2.read()[0].to_bool())? ap_const_lv32_0: current_block_write_fu_709_p2.read());
}

void ConvolutionInputGene::thread_current_block_write_7_fu_667_p2() {
    current_block_write_7_fu_667_p2 = (!current_block_write_5_fu_96.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(current_block_write_5_fu_96.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_current_block_write_8_fu_679_p3() {
    current_block_write_8_fu_679_p3 = (!icmp_ln257_fu_673_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln257_fu_673_p2.read()[0].to_bool())? ap_const_lv32_0: current_block_write_7_fu_667_p2.read());
}

void ConvolutionInputGene::thread_current_block_write_9_fu_687_p3() {
    current_block_write_9_fu_687_p3 = (!icmp_ln252_reg_874.read()[0].is_01())? sc_lv<32>(): ((icmp_ln252_reg_874.read()[0].to_bool())? current_block_write_8_fu_679_p3.read(): current_block_write_5_fu_96.read());
}

void ConvolutionInputGene::thread_current_block_write_fu_709_p2() {
    current_block_write_fu_709_p2 = (!current_block_write_5_fu_96.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(current_block_write_5_fu_96.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_current_line_in_bloc_fu_394_p2() {
    current_line_in_bloc_fu_394_p2 = (!add_ln220_fu_388_p2.read().is_01() || !k_x_1_fu_88.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln220_fu_388_p2.read()) + sc_biguint<32>(k_x_1_fu_88.read()));
}

void ConvolutionInputGene::thread_grp_fu_262_p2() {
    grp_fu_262_p2 = (!current_line_2_fu_100.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(current_line_2_fu_100.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_i_fu_624_p3() {
    i_fu_624_p3 = (!icmp_ln197_fu_336_p2.read()[0].is_01())? sc_lv<7>(): ((icmp_ln197_fu_336_p2.read()[0].to_bool())? ap_const_lv7_1: add_ln197_fu_618_p2.read());
}

void ConvolutionInputGene::thread_icmp_ln196_fu_319_p2() {
    icmp_ln196_fu_319_p2 = (!indvar_flatten_reg_197.read().is_01() || !bound_reg_821.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_197.read() == bound_reg_821.read());
}

void ConvolutionInputGene::thread_icmp_ln197_fu_336_p2() {
    icmp_ln197_fu_336_p2 = (!i_0_i_reg_208.read().is_01() || !ap_const_lv7_6E.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_208.read() == ap_const_lv7_6E);
}

void ConvolutionInputGene::thread_icmp_ln199_fu_355_p2() {
    icmp_ln199_fu_355_p2 = (!inp_1_fu_84.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): (sc_biguint<32>(inp_1_fu_84.read()) < sc_biguint<32>(ap_const_lv32_A));
}

void ConvolutionInputGene::thread_icmp_ln205_fu_274_p2() {
    icmp_ln205_fu_274_p2 = (!grp_fu_262_p2.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): sc_lv<1>(grp_fu_262_p2.read() == ap_const_lv32_A);
}

void ConvolutionInputGene::thread_icmp_ln208_fu_715_p2() {
    icmp_ln208_fu_715_p2 = (!current_block_write_fu_709_p2.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): sc_lv<1>(current_block_write_fu_709_p2.read() == ap_const_lv32_2);
}

void ConvolutionInputGene::thread_icmp_ln215_fu_364_p2() {
    icmp_ln215_fu_364_p2 = (!counter_internal_blo_fu_104.read().is_01() || !ap_const_lv32_9.is_01())? sc_lv<1>(): (sc_biguint<32>(counter_internal_blo_fu_104.read()) < sc_biguint<32>(ap_const_lv32_9));
}

void ConvolutionInputGene::thread_icmp_ln224_fu_412_p2() {
    icmp_ln224_fu_412_p2 = (!count_simd_1_fu_92.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(count_simd_1_fu_92.read() == ap_const_lv32_0);
}

void ConvolutionInputGene::thread_icmp_ln227_fu_429_p2() {
    icmp_ln227_fu_429_p2 = (!k_x_1_fu_88.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(k_x_1_fu_88.read() == ap_const_lv32_0);
}

void ConvolutionInputGene::thread_icmp_ln230_fu_443_p2() {
    icmp_ln230_fu_443_p2 = (!k_y_1_fu_80.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(k_y_1_fu_80.read() == ap_const_lv32_0);
}

void ConvolutionInputGene::thread_icmp_ln233_fu_463_p2() {
    icmp_ln233_fu_463_p2 = (!ofm_x_fu_457_p2.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): sc_lv<1>(ofm_x_fu_457_p2.read() == ap_const_lv32_A);
}

void ConvolutionInputGene::thread_icmp_ln236_fu_483_p2() {
    icmp_ln236_fu_483_p2 = (!ofm_y_fu_477_p2.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): sc_lv<1>(ofm_y_fu_477_p2.read() == ap_const_lv32_A);
}

void ConvolutionInputGene::thread_icmp_ln245_fu_515_p2() {
    icmp_ln245_fu_515_p2 = (!select_ln197_fu_342_p3.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): (sc_biguint<32>(select_ln197_fu_342_p3.read()) < sc_biguint<32>(ap_const_lv32_A));
}

void ConvolutionInputGene::thread_icmp_ln252_fu_268_p2() {
    icmp_ln252_fu_268_p2 = (!grp_fu_262_p2.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): sc_lv<1>(grp_fu_262_p2.read() == ap_const_lv32_A);
}

void ConvolutionInputGene::thread_icmp_ln257_fu_673_p2() {
    icmp_ln257_fu_673_p2 = (!current_block_write_7_fu_667_p2.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): sc_lv<1>(current_block_write_7_fu_667_p2.read() == ap_const_lv32_2);
}

void ConvolutionInputGene::thread_icmp_ln264_fu_572_p2() {
    icmp_ln264_fu_572_p2 = (!counter_internal_blo_3_fu_566_p2.read().is_01() || !ap_const_lv32_9.is_01())? sc_lv<1>(): sc_lv<1>(counter_internal_blo_3_fu_566_p2.read() == ap_const_lv32_9);
}

void ConvolutionInputGene::thread_in_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read())))) {
        in_V_V_blk_n = in_V_V_empty_n.read();
    } else {
        in_V_V_blk_n = ap_const_logic_1;
    }
}

void ConvolutionInputGene::thread_in_V_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op154_read_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        in_V_V_read = ap_const_logic_1;
    } else {
        in_V_V_read = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_inp_fu_591_p2() {
    inp_fu_591_p2 = (!inp_1_fu_84.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(inp_1_fu_84.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_inputBuf_0_V_address0() {
    inputBuf_0_V_address0 =  (sc_lv<4>) (zext_ln221_fu_400_p1.read());
}

void ConvolutionInputGene::thread_inputBuf_0_V_address1() {
    if (esl_seteq<1,1,1>(ap_condition_51.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_705_p1.read()))) {
            inputBuf_0_V_address1 =  (sc_lv<4>) (zext_ln202_fu_699_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_337.read(), ap_const_boolean_1)) {
            inputBuf_0_V_address1 =  (sc_lv<4>) (zext_ln248_fu_654_p1.read());
        } else {
            inputBuf_0_V_address1 = "XXXX";
        }
    } else {
        inputBuf_0_V_address1 = "XXXX";
    }
}

void ConvolutionInputGene::thread_inputBuf_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        inputBuf_0_V_ce0 = ap_const_logic_1;
    } else {
        inputBuf_0_V_ce0 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_inputBuf_0_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_660_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_705_p1.read())))) {
        inputBuf_0_V_ce1 = ap_const_logic_1;
    } else {
        inputBuf_0_V_ce1 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_inputBuf_0_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_660_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_705_p1.read())))) {
        inputBuf_0_V_we1 = ap_const_logic_1;
    } else {
        inputBuf_0_V_we1 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_inputBuf_1_V_address0() {
    inputBuf_1_V_address0 =  (sc_lv<4>) (zext_ln221_fu_400_p1.read());
}

void ConvolutionInputGene::thread_inputBuf_1_V_address1() {
    if (esl_seteq<1,1,1>(ap_condition_51.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_705_p1.read()))) {
            inputBuf_1_V_address1 =  (sc_lv<4>) (zext_ln202_fu_699_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_348.read(), ap_const_boolean_1)) {
            inputBuf_1_V_address1 =  (sc_lv<4>) (zext_ln248_fu_654_p1.read());
        } else {
            inputBuf_1_V_address1 = "XXXX";
        }
    } else {
        inputBuf_1_V_address1 = "XXXX";
    }
}

void ConvolutionInputGene::thread_inputBuf_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        inputBuf_1_V_ce0 = ap_const_logic_1;
    } else {
        inputBuf_1_V_ce0 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_inputBuf_1_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_660_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_705_p1.read())))) {
        inputBuf_1_V_ce1 = ap_const_logic_1;
    } else {
        inputBuf_1_V_ce1 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_inputBuf_1_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln245_reg_870.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_660_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_705_p1.read())))) {
        inputBuf_1_V_we1 = ap_const_logic_1;
    } else {
        inputBuf_1_V_we1 = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_k_x_fu_423_p2() {
    k_x_fu_423_p2 = (!k_x_1_fu_88.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(k_x_1_fu_88.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_k_y_fu_382_p2() {
    k_y_fu_382_p2 = (!ap_const_lv32_1.is_01() || !k_y_1_fu_80.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(k_y_1_fu_80.read()));
}

void ConvolutionInputGene::thread_numReps_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        numReps_blk_n = numReps_empty_n.read();
    } else {
        numReps_blk_n = ap_const_logic_1;
    }
}

void ConvolutionInputGene::thread_numReps_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
        numReps_read = ap_const_logic_1;
    } else {
        numReps_read = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_ofm_x_fu_457_p2() {
    ofm_x_fu_457_p2 = (!ofm_x_1_fu_76.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(ofm_x_1_fu_76.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_ofm_y_fu_477_p2() {
    ofm_y_fu_477_p2 = (!ofm_y_1_i_fu_72.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(ofm_y_1_i_fu_72.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln199_reg_835.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln215_reg_839.read()))) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void ConvolutionInputGene::thread_out_V_V_din() {
    out_V_V_din = (!xor_ln221_fu_639_p2.read()[0].is_01())? sc_lv<3>(): ((xor_ln221_fu_639_p2.read()[0].to_bool())? inputBuf_0_V_q0.read(): inputBuf_1_V_q0.read());
}

void ConvolutionInputGene::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op151_write_state4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void ConvolutionInputGene::thread_read_block_3_fu_541_p3() {
    read_block_3_fu_541_p3 = (!icmp_ln252_fu_268_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln252_fu_268_p2.read()[0].to_bool())? add_ln255_fu_527_p2.read(): trunc_ln197_fu_351_p1.read());
}

void ConvolutionInputGene::thread_read_block_fu_607_p2() {
    read_block_fu_607_p2 = (!select_ln197_fu_342_p3.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(select_ln197_fu_342_p3.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ConvolutionInputGene::thread_select_ln197_fu_342_p3() {
    select_ln197_fu_342_p3 = (!icmp_ln197_fu_336_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln197_fu_336_p2.read()[0].to_bool())? ap_const_lv32_0: read_block_2_fu_68.read());
}

void ConvolutionInputGene::thread_select_ln236_1_fu_497_p3() {
    select_ln236_1_fu_497_p3 = (!icmp_ln236_fu_483_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln236_fu_483_p2.read()[0].to_bool())? ap_const_lv32_0: ofm_y_fu_477_p2.read());
}

void ConvolutionInputGene::thread_select_ln236_fu_489_p3() {
    select_ln236_fu_489_p3 = (!icmp_ln236_fu_483_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln236_fu_483_p2.read()[0].to_bool())? ap_const_lv32_0: inp_1_fu_84.read());
}

void ConvolutionInputGene::thread_select_ln252_fu_533_p3() {
    select_ln252_fu_533_p3 = (!icmp_ln252_fu_268_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln252_fu_268_p2.read()[0].to_bool())? ap_const_lv32_0: grp_fu_262_p2.read());
}

void ConvolutionInputGene::thread_select_ln264_fu_578_p3() {
    select_ln264_fu_578_p3 = (!icmp_ln264_fu_572_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln264_fu_572_p2.read()[0].to_bool())? ap_const_lv32_0: counter_internal_blo_3_fu_566_p2.read());
}

void ConvolutionInputGene::thread_trunc_ln197_fu_351_p1() {
    trunc_ln197_fu_351_p1 = select_ln197_fu_342_p3.read().range(4-1, 0);
}

void ConvolutionInputGene::thread_trunc_ln216_1_fu_635_p1() {
    trunc_ln216_1_fu_635_p1 = current_block_write_5_fu_96.read().range(1-1, 0);
}

void ConvolutionInputGene::thread_trunc_ln216_fu_632_p1() {
    trunc_ln216_fu_632_p1 = k_y_1_load_reg_843.read().range(1-1, 0);
}

void ConvolutionInputGene::thread_trunc_ln321_1_fu_660_p1() {
    trunc_ln321_1_fu_660_p1 = current_block_write_5_fu_96.read().range(1-1, 0);
}

void ConvolutionInputGene::thread_trunc_ln321_fu_705_p1() {
    trunc_ln321_fu_705_p1 = current_block_write_5_fu_96.read().range(1-1, 0);
}

void ConvolutionInputGene::thread_xor_ln221_fu_639_p2() {
    xor_ln221_fu_639_p2 = (trunc_ln216_1_fu_635_p1.read() ^ trunc_ln216_fu_632_p1.read());
}

void ConvolutionInputGene::thread_zext_ln202_fu_699_p1() {
    zext_ln202_fu_699_p1 = esl_zext<64,32>(reg_286.read());
}

void ConvolutionInputGene::thread_zext_ln221_fu_400_p1() {
    zext_ln221_fu_400_p1 = esl_zext<64,32>(current_line_in_bloc_fu_394_p2.read());
}

void ConvolutionInputGene::thread_zext_ln248_fu_654_p1() {
    zext_ln248_fu_654_p1 = esl_zext<64,32>(reg_286.read());
}

void ConvolutionInputGene::thread_zext_ln252_fu_549_p1() {
    zext_ln252_fu_549_p1 = esl_zext<32,4>(read_block_3_fu_541_p3.read());
}

void ConvolutionInputGene::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln196_fu_319_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln196_fu_319_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

