// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2023.1 (64-bit)
// Tool Version Limit: 2023.05
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// 
// ==============================================================

extern "C" void AESL_WRAP_fc1full_top (
volatile void* in_r,
volatile void* out_0,
volatile void* out_1,
volatile void* out_2,
volatile void* out_3,
volatile void* out_4,
volatile void* out_5,
volatile void* out_6,
volatile void* out_7,
volatile void* out_8,
volatile void* out_9,
volatile void* out_10,
volatile void* out_11,
volatile void* out_12,
volatile void* out_13,
volatile void* out_14,
volatile void* out_15,
volatile void* out_16,
volatile void* out_17,
volatile void* out_18,
volatile void* out_19,
volatile void* out_20,
volatile void* out_21,
volatile void* out_22,
volatile void* out_23,
volatile void* out_24,
volatile void* out_25,
volatile void* out_26,
volatile void* out_27,
volatile void* out_28,
volatile void* out_29,
volatile void* out_30,
volatile void* out_31,
volatile void* out_32,
volatile void* out_33,
volatile void* out_34,
volatile void* out_35,
volatile void* out_36,
volatile void* out_37,
volatile void* out_38,
volatile void* out_39,
volatile void* out_40,
volatile void* out_41,
volatile void* out_42,
volatile void* out_43,
volatile void* out_44,
volatile void* out_45,
volatile void* out_46,
volatile void* out_47,
volatile void* out_48,
volatile void* out_49,
volatile void* out_50,
volatile void* out_51,
volatile void* out_52,
volatile void* out_53,
volatile void* out_54,
volatile void* out_55,
volatile void* out_56,
volatile void* out_57,
volatile void* out_58,
volatile void* out_59,
volatile void* out_60,
volatile void* out_61,
volatile void* out_62,
volatile void* out_63);
