// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2023.1 (64-bit)
// Tool Version Limit: 2023.05
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// 
// ==============================================================

extern "C" void AESL_WRAP_fc2full_top (
volatile void* in_0,
volatile void* in_1,
volatile void* in_2,
volatile void* in_3,
volatile void* in_4,
volatile void* in_5,
volatile void* in_6,
volatile void* in_7,
volatile void* in_8,
volatile void* in_9,
volatile void* in_10,
volatile void* in_11,
volatile void* in_12,
volatile void* in_13,
volatile void* in_14,
volatile void* in_15,
volatile void* in_16,
volatile void* in_17,
volatile void* in_18,
volatile void* in_19,
volatile void* in_20,
volatile void* in_21,
volatile void* in_22,
volatile void* in_23,
volatile void* in_24,
volatile void* in_25,
volatile void* in_26,
volatile void* in_27,
volatile void* in_28,
volatile void* in_29,
volatile void* in_30,
volatile void* in_31,
volatile void* in_32,
volatile void* in_33,
volatile void* in_34,
volatile void* in_35,
volatile void* in_36,
volatile void* in_37,
volatile void* in_38,
volatile void* in_39,
volatile void* in_40,
volatile void* in_41,
volatile void* in_42,
volatile void* in_43,
volatile void* in_44,
volatile void* in_45,
volatile void* in_46,
volatile void* in_47,
volatile void* in_48,
volatile void* in_49,
volatile void* in_50,
volatile void* in_51,
volatile void* in_52,
volatile void* in_53,
volatile void* in_54,
volatile void* in_55,
volatile void* in_56,
volatile void* in_57,
volatile void* in_58,
volatile void* in_59,
volatile void* in_60,
volatile void* in_61,
volatile void* in_62,
volatile void* in_63,
volatile void* out_0,
volatile void* out_1,
volatile void* out_2,
volatile void* out_3,
volatile void* out_4);
