// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fc_finn_top_load_weights_once_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_22_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fc_weights_0_address0,
        fc_weights_0_ce0,
        fc_weights_0_we0,
        fc_weights_0_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] fc_weights_0_address0;
output   fc_weights_0_ce0;
output   fc_weights_0_we0;
output  [1:0] fc_weights_0_d0;

reg ap_idle;
reg fc_weights_0_ce0;
reg fc_weights_0_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln21_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] FC_W_address0;
reg    FC_W_ce0;
wire   [1:0] FC_W_q0;
wire   [63:0] zext_ln25_1_fu_167_p1;
reg   [63:0] zext_ln25_1_reg_217;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
reg   [3:0] col_fu_42;
wire   [3:0] add_ln22_fu_172_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_col_load;
reg   [2:0] row_fu_46;
wire   [2:0] select_ln21_1_fu_137_p3;
reg   [2:0] ap_sig_allocacmp_row_load;
reg   [5:0] indvar_flatten_fu_50;
wire   [5:0] add_ln21_1_fu_105_p2;
reg   [5:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln22_fu_123_p2;
wire   [2:0] add_ln21_fu_117_p2;
wire   [1:0] trunc_ln25_fu_145_p1;
wire   [3:0] select_ln21_fu_129_p3;
wire   [4:0] tmp_fu_149_p3;
wire   [4:0] zext_ln25_fu_157_p1;
wire   [4:0] add_ln25_fu_161_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fc_finn_top_load_weights_once_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_22_2_FC_W_ROM_AUTO_1R #(
    .DataWidth( 2 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
FC_W_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FC_W_address0),
    .ce0(FC_W_ce0),
    .q0(FC_W_q0)
);

fc_finn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_42 <= add_ln22_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_42 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_50 <= add_ln21_1_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_50 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            row_fu_46 <= select_ln21_1_fu_137_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_46 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_99_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln25_1_reg_217[4 : 0] <= zext_ln25_1_fu_167_p1[4 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        FC_W_ce0 = 1'b1;
    end else begin
        FC_W_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col_load = 4'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_42;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_50;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_row_load = 3'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc_weights_0_ce0 = 1'b1;
    end else begin
        fc_weights_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc_weights_0_we0 = 1'b1;
    end else begin
        fc_weights_0_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FC_W_address0 = zext_ln25_1_fu_167_p1;

assign add_ln21_1_fu_105_p2 = (ap_sig_allocacmp_indvar_flatten_load + 6'd1);

assign add_ln21_fu_117_p2 = (ap_sig_allocacmp_row_load + 3'd1);

assign add_ln22_fu_172_p2 = (select_ln21_fu_129_p3 + 4'd1);

assign add_ln25_fu_161_p2 = (tmp_fu_149_p3 + zext_ln25_fu_157_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign fc_weights_0_address0 = zext_ln25_1_reg_217;

assign fc_weights_0_d0 = FC_W_q0;

assign icmp_ln21_fu_99_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_123_p2 = ((ap_sig_allocacmp_col_load == 4'd8) ? 1'b1 : 1'b0);

assign select_ln21_1_fu_137_p3 = ((icmp_ln22_fu_123_p2[0:0] == 1'b1) ? add_ln21_fu_117_p2 : ap_sig_allocacmp_row_load);

assign select_ln21_fu_129_p3 = ((icmp_ln22_fu_123_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_col_load);

assign tmp_fu_149_p3 = {{trunc_ln25_fu_145_p1}, {3'd0}};

assign trunc_ln25_fu_145_p1 = select_ln21_1_fu_137_p3[1:0];

assign zext_ln25_1_fu_167_p1 = add_ln25_fu_161_p2;

assign zext_ln25_fu_157_p1 = select_ln21_fu_129_p3;

always @ (posedge ap_clk) begin
    zext_ln25_1_reg_217[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //fc_finn_top_load_weights_once_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_22_2
