-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fc2full_top_fc2full_top_Pipeline_VITIS_LOOP_131_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_empty_n : IN STD_LOGIC;
    in_stream_read : OUT STD_LOGIC;
    out_stream_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_full_n : IN STD_LOGIC;
    out_stream_write : OUT STD_LOGIC;
    fc2_weights_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    fc2_weights_0_ce0 : OUT STD_LOGIC;
    fc2_weights_0_q0 : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of fc2full_top_fc2full_top_Pipeline_VITIS_LOOP_131_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_3D : STD_LOGIC_VECTOR (5 downto 0) := "111101";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv6_3A : STD_LOGIC_VECTOR (5 downto 0) := "111010";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln131_reg_2093 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_reg_2107 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op181_read_state3 : BOOLEAN;
    signal icmp_ln172_reg_2120 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln131_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal in_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln123_fu_762_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln123_reg_2097 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln123_1_fu_766_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln123_1_reg_2102 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln134_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_reg_2111 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln172_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_inElem_phi_fu_513_p130 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_inElem_reg_510 : STD_LOGIC_VECTOR (0 downto 0);
    signal inElem_1_fu_1058_p66 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_outElem_phi_fu_712_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_outElem_reg_709 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln179_fu_1601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal idxprom4_i_i_fu_785_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln165_fu_1595_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sf_fu_208 : STD_LOGIC_VECTOR (31 downto 0);
    signal sf_3_fu_796_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal tile_fu_212 : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_1_fu_790_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_2_fu_838_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_1_fu_216 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_2_fu_756_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal inputBuf_fu_220 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_1_fu_224 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_2_fu_228 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_3_fu_232 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_4_fu_236 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_5_fu_240 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_6_fu_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_7_fu_248 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_8_fu_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_9_fu_256 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_10_fu_260 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_11_fu_264 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_12_fu_268 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_13_fu_272 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_14_fu_276 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_15_fu_280 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_16_fu_284 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_17_fu_288 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_18_fu_292 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_19_fu_296 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_20_fu_300 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_21_fu_304 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_22_fu_308 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_23_fu_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_24_fu_316 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_25_fu_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_26_fu_324 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_27_fu_328 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_28_fu_332 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_29_fu_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_30_fu_340 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_31_fu_344 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_32_fu_348 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_33_fu_352 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_34_fu_356 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_35_fu_360 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_36_fu_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_37_fu_368 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_38_fu_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_39_fu_376 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_40_fu_380 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_41_fu_384 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_42_fu_388 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_43_fu_392 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_44_fu_396 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_45_fu_400 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_46_fu_404 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_47_fu_408 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_48_fu_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_49_fu_416 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_50_fu_420 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_51_fu_424 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_52_fu_428 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_53_fu_432 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_54_fu_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_55_fu_440 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_56_fu_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_57_fu_448 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_58_fu_452 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_59_fu_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_60_fu_460 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_61_fu_464 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_62_fu_468 : STD_LOGIC_VECTOR (0 downto 0);
    signal inputBuf_63_fu_472 : STD_LOGIC_VECTOR (0 downto 0);
    signal nf_fu_476 : STD_LOGIC_VECTOR (31 downto 0);
    signal nf_5_fu_830_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_i2_i13_i_fu_480 : STD_LOGIC_VECTOR (15 downto 0);
    signal temp_1_fu_1561_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_conv_i2_i13_i_load : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal nf_4_fu_818_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln192_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_fu_1532_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln2_fu_1547_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln155_fu_1557_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal temp_3_fu_1575_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_1583_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln165_fu_1591_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_1271 : BOOLEAN;
    signal ap_condition_1274 : BOOLEAN;
    signal ap_condition_1281 : BOOLEAN;
    signal ap_condition_1284 : BOOLEAN;
    signal ap_condition_1287 : BOOLEAN;
    signal ap_condition_1290 : BOOLEAN;
    signal ap_condition_1293 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component fc2full_top_mux_64_6_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        din33_WIDTH : INTEGER;
        din34_WIDTH : INTEGER;
        din35_WIDTH : INTEGER;
        din36_WIDTH : INTEGER;
        din37_WIDTH : INTEGER;
        din38_WIDTH : INTEGER;
        din39_WIDTH : INTEGER;
        din40_WIDTH : INTEGER;
        din41_WIDTH : INTEGER;
        din42_WIDTH : INTEGER;
        din43_WIDTH : INTEGER;
        din44_WIDTH : INTEGER;
        din45_WIDTH : INTEGER;
        din46_WIDTH : INTEGER;
        din47_WIDTH : INTEGER;
        din48_WIDTH : INTEGER;
        din49_WIDTH : INTEGER;
        din50_WIDTH : INTEGER;
        din51_WIDTH : INTEGER;
        din52_WIDTH : INTEGER;
        din53_WIDTH : INTEGER;
        din54_WIDTH : INTEGER;
        din55_WIDTH : INTEGER;
        din56_WIDTH : INTEGER;
        din57_WIDTH : INTEGER;
        din58_WIDTH : INTEGER;
        din59_WIDTH : INTEGER;
        din60_WIDTH : INTEGER;
        din61_WIDTH : INTEGER;
        din62_WIDTH : INTEGER;
        din63_WIDTH : INTEGER;
        din64_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        din9 : IN STD_LOGIC_VECTOR (0 downto 0);
        din10 : IN STD_LOGIC_VECTOR (0 downto 0);
        din11 : IN STD_LOGIC_VECTOR (0 downto 0);
        din12 : IN STD_LOGIC_VECTOR (0 downto 0);
        din13 : IN STD_LOGIC_VECTOR (0 downto 0);
        din14 : IN STD_LOGIC_VECTOR (0 downto 0);
        din15 : IN STD_LOGIC_VECTOR (0 downto 0);
        din16 : IN STD_LOGIC_VECTOR (0 downto 0);
        din17 : IN STD_LOGIC_VECTOR (0 downto 0);
        din18 : IN STD_LOGIC_VECTOR (0 downto 0);
        din19 : IN STD_LOGIC_VECTOR (0 downto 0);
        din20 : IN STD_LOGIC_VECTOR (0 downto 0);
        din21 : IN STD_LOGIC_VECTOR (0 downto 0);
        din22 : IN STD_LOGIC_VECTOR (0 downto 0);
        din23 : IN STD_LOGIC_VECTOR (0 downto 0);
        din24 : IN STD_LOGIC_VECTOR (0 downto 0);
        din25 : IN STD_LOGIC_VECTOR (0 downto 0);
        din26 : IN STD_LOGIC_VECTOR (0 downto 0);
        din27 : IN STD_LOGIC_VECTOR (0 downto 0);
        din28 : IN STD_LOGIC_VECTOR (0 downto 0);
        din29 : IN STD_LOGIC_VECTOR (0 downto 0);
        din30 : IN STD_LOGIC_VECTOR (0 downto 0);
        din31 : IN STD_LOGIC_VECTOR (0 downto 0);
        din32 : IN STD_LOGIC_VECTOR (0 downto 0);
        din33 : IN STD_LOGIC_VECTOR (0 downto 0);
        din34 : IN STD_LOGIC_VECTOR (0 downto 0);
        din35 : IN STD_LOGIC_VECTOR (0 downto 0);
        din36 : IN STD_LOGIC_VECTOR (0 downto 0);
        din37 : IN STD_LOGIC_VECTOR (0 downto 0);
        din38 : IN STD_LOGIC_VECTOR (0 downto 0);
        din39 : IN STD_LOGIC_VECTOR (0 downto 0);
        din40 : IN STD_LOGIC_VECTOR (0 downto 0);
        din41 : IN STD_LOGIC_VECTOR (0 downto 0);
        din42 : IN STD_LOGIC_VECTOR (0 downto 0);
        din43 : IN STD_LOGIC_VECTOR (0 downto 0);
        din44 : IN STD_LOGIC_VECTOR (0 downto 0);
        din45 : IN STD_LOGIC_VECTOR (0 downto 0);
        din46 : IN STD_LOGIC_VECTOR (0 downto 0);
        din47 : IN STD_LOGIC_VECTOR (0 downto 0);
        din48 : IN STD_LOGIC_VECTOR (0 downto 0);
        din49 : IN STD_LOGIC_VECTOR (0 downto 0);
        din50 : IN STD_LOGIC_VECTOR (0 downto 0);
        din51 : IN STD_LOGIC_VECTOR (0 downto 0);
        din52 : IN STD_LOGIC_VECTOR (0 downto 0);
        din53 : IN STD_LOGIC_VECTOR (0 downto 0);
        din54 : IN STD_LOGIC_VECTOR (0 downto 0);
        din55 : IN STD_LOGIC_VECTOR (0 downto 0);
        din56 : IN STD_LOGIC_VECTOR (0 downto 0);
        din57 : IN STD_LOGIC_VECTOR (0 downto 0);
        din58 : IN STD_LOGIC_VECTOR (0 downto 0);
        din59 : IN STD_LOGIC_VECTOR (0 downto 0);
        din60 : IN STD_LOGIC_VECTOR (0 downto 0);
        din61 : IN STD_LOGIC_VECTOR (0 downto 0);
        din62 : IN STD_LOGIC_VECTOR (0 downto 0);
        din63 : IN STD_LOGIC_VECTOR (0 downto 0);
        din64 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fc2full_top_mux_5_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fc2full_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_64_6_1_1_1_U71 : component fc2full_top_mux_64_6_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 1,
        din5_WIDTH => 1,
        din6_WIDTH => 1,
        din7_WIDTH => 1,
        din8_WIDTH => 1,
        din9_WIDTH => 1,
        din10_WIDTH => 1,
        din11_WIDTH => 1,
        din12_WIDTH => 1,
        din13_WIDTH => 1,
        din14_WIDTH => 1,
        din15_WIDTH => 1,
        din16_WIDTH => 1,
        din17_WIDTH => 1,
        din18_WIDTH => 1,
        din19_WIDTH => 1,
        din20_WIDTH => 1,
        din21_WIDTH => 1,
        din22_WIDTH => 1,
        din23_WIDTH => 1,
        din24_WIDTH => 1,
        din25_WIDTH => 1,
        din26_WIDTH => 1,
        din27_WIDTH => 1,
        din28_WIDTH => 1,
        din29_WIDTH => 1,
        din30_WIDTH => 1,
        din31_WIDTH => 1,
        din32_WIDTH => 1,
        din33_WIDTH => 1,
        din34_WIDTH => 1,
        din35_WIDTH => 1,
        din36_WIDTH => 1,
        din37_WIDTH => 1,
        din38_WIDTH => 1,
        din39_WIDTH => 1,
        din40_WIDTH => 1,
        din41_WIDTH => 1,
        din42_WIDTH => 1,
        din43_WIDTH => 1,
        din44_WIDTH => 1,
        din45_WIDTH => 1,
        din46_WIDTH => 1,
        din47_WIDTH => 1,
        din48_WIDTH => 1,
        din49_WIDTH => 1,
        din50_WIDTH => 1,
        din51_WIDTH => 1,
        din52_WIDTH => 1,
        din53_WIDTH => 1,
        din54_WIDTH => 1,
        din55_WIDTH => 1,
        din56_WIDTH => 1,
        din57_WIDTH => 1,
        din58_WIDTH => 1,
        din59_WIDTH => 1,
        din60_WIDTH => 1,
        din61_WIDTH => 1,
        din62_WIDTH => 1,
        din63_WIDTH => 1,
        din64_WIDTH => 6,
        dout_WIDTH => 1)
    port map (
        din0 => inputBuf_fu_220,
        din1 => inputBuf_1_fu_224,
        din2 => inputBuf_2_fu_228,
        din3 => inputBuf_3_fu_232,
        din4 => inputBuf_4_fu_236,
        din5 => inputBuf_5_fu_240,
        din6 => inputBuf_6_fu_244,
        din7 => inputBuf_7_fu_248,
        din8 => inputBuf_8_fu_252,
        din9 => inputBuf_9_fu_256,
        din10 => inputBuf_10_fu_260,
        din11 => inputBuf_11_fu_264,
        din12 => inputBuf_12_fu_268,
        din13 => inputBuf_13_fu_272,
        din14 => inputBuf_14_fu_276,
        din15 => inputBuf_15_fu_280,
        din16 => inputBuf_16_fu_284,
        din17 => inputBuf_17_fu_288,
        din18 => inputBuf_18_fu_292,
        din19 => inputBuf_19_fu_296,
        din20 => inputBuf_20_fu_300,
        din21 => inputBuf_21_fu_304,
        din22 => inputBuf_22_fu_308,
        din23 => inputBuf_23_fu_312,
        din24 => inputBuf_24_fu_316,
        din25 => inputBuf_25_fu_320,
        din26 => inputBuf_26_fu_324,
        din27 => inputBuf_27_fu_328,
        din28 => inputBuf_28_fu_332,
        din29 => inputBuf_29_fu_336,
        din30 => inputBuf_30_fu_340,
        din31 => inputBuf_31_fu_344,
        din32 => inputBuf_32_fu_348,
        din33 => inputBuf_33_fu_352,
        din34 => inputBuf_34_fu_356,
        din35 => inputBuf_35_fu_360,
        din36 => inputBuf_36_fu_364,
        din37 => inputBuf_37_fu_368,
        din38 => inputBuf_38_fu_372,
        din39 => inputBuf_39_fu_376,
        din40 => inputBuf_40_fu_380,
        din41 => inputBuf_41_fu_384,
        din42 => inputBuf_42_fu_388,
        din43 => inputBuf_43_fu_392,
        din44 => inputBuf_44_fu_396,
        din45 => inputBuf_45_fu_400,
        din46 => inputBuf_46_fu_404,
        din47 => inputBuf_47_fu_408,
        din48 => inputBuf_48_fu_412,
        din49 => inputBuf_49_fu_416,
        din50 => inputBuf_50_fu_420,
        din51 => inputBuf_51_fu_424,
        din52 => inputBuf_52_fu_428,
        din53 => inputBuf_53_fu_432,
        din54 => inputBuf_54_fu_436,
        din55 => inputBuf_55_fu_440,
        din56 => inputBuf_56_fu_444,
        din57 => inputBuf_57_fu_448,
        din58 => inputBuf_58_fu_452,
        din59 => inputBuf_59_fu_456,
        din60 => inputBuf_60_fu_460,
        din61 => inputBuf_61_fu_464,
        din62 => inputBuf_62_fu_468,
        din63 => inputBuf_63_fu_472,
        din64 => trunc_ln123_reg_2097,
        dout => inElem_1_fu_1058_p66);

    mux_5_3_16_1_1_U72 : component fc2full_top_mux_5_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_4,
        din1 => void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_3,
        din2 => void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_2,
        din3 => void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_1,
        din4 => void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr,
        din5 => trunc_ln123_1_reg_2102,
        dout => temp_fu_1532_p7);

    flow_control_loop_pipe_sequential_init_U : component fc2full_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    conv_i2_i13_i_fu_480_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                conv_i2_i13_i_fu_480 <= add_ln165_fu_1595_p2;
            end if;
        end if;
    end process;

    i_1_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_216 <= ap_const_lv9_0;
                elsif (((icmp_ln131_fu_750_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_1_fu_216 <= i_2_fu_756_p2;
                end if;
            end if; 
        end if;
    end process;

    nf_fu_476_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nf_fu_476 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_1271)) then 
                    nf_fu_476 <= nf_5_fu_830_p3;
                end if;
            end if; 
        end if;
    end process;

    sf_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln131_fu_750_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_fu_802_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                sf_fu_208 <= ap_const_lv32_0;
            elsif (((icmp_ln131_fu_750_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_fu_802_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                sf_fu_208 <= sf_3_fu_796_p2;
            end if; 
        end if;
    end process;

    tile_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    tile_fu_212 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_1271)) then 
                    tile_fu_212 <= tile_2_fu_838_p3;
                elsif ((ap_const_boolean_1 = ap_condition_1274)) then 
                    tile_fu_212 <= tile_1_fu_790_p2;
                end if;
            end if; 
        end if;
    end process;

    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1281)) then
                if ((icmp_ln179_fu_1601_p2 = ap_const_lv1_1)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr <= ap_const_lv16_0;
                elsif ((icmp_ln179_fu_1601_p2 = ap_const_lv1_0)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr <= add_ln165_fu_1595_p2;
                end if;
            end if; 
        end if;
    end process;

    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1284)) then
                if ((icmp_ln179_fu_1601_p2 = ap_const_lv1_1)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_1 <= ap_const_lv16_0;
                elsif ((icmp_ln179_fu_1601_p2 = ap_const_lv1_0)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_1 <= add_ln165_fu_1595_p2;
                end if;
            end if; 
        end if;
    end process;

    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1287)) then
                if ((icmp_ln179_fu_1601_p2 = ap_const_lv1_1)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_2 <= ap_const_lv16_0;
                elsif ((icmp_ln179_fu_1601_p2 = ap_const_lv1_0)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_2 <= add_ln165_fu_1595_p2;
                end if;
            end if; 
        end if;
    end process;

    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1290)) then
                if ((icmp_ln179_fu_1601_p2 = ap_const_lv1_1)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_3 <= ap_const_lv16_0;
                elsif ((icmp_ln179_fu_1601_p2 = ap_const_lv1_0)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_3 <= add_ln165_fu_1595_p2;
                end if;
            end if; 
        end if;
    end process;

    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1293)) then
                if ((icmp_ln179_fu_1601_p2 = ap_const_lv1_1)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_4 <= ap_const_lv16_0;
                elsif ((icmp_ln179_fu_1601_p2 = ap_const_lv1_0)) then 
                    void_Matrix_Vector_Activate_Batch_stream_stream_FixedPointWeightsSp_const_Thr_4 <= add_ln165_fu_1595_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln131_reg_2093 <= icmp_ln131_fu_750_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln131_fu_750_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln134_reg_2107 <= icmp_ln134_fu_770_p2;
                icmp_ln149_reg_2111 <= icmp_ln149_fu_776_p2;
                icmp_ln172_reg_2120 <= icmp_ln172_fu_802_p2;
                trunc_ln123_1_reg_2102 <= trunc_ln123_1_fu_766_p1;
                trunc_ln123_reg_2097 <= trunc_ln123_fu_762_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_10_fu_260 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_11_fu_264 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_12_fu_268 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_13_fu_272 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_14_fu_276 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_15_fu_280 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_10) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_16_fu_284 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_11) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_17_fu_288 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_12) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_18_fu_292 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_13) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_19_fu_296 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_1_fu_224 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_14) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_20_fu_300 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_15) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_21_fu_304 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_16) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_22_fu_308 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_17) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_23_fu_312 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_18) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_24_fu_316 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_19) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_25_fu_320 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_26_fu_324 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_27_fu_328 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_28_fu_332 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_29_fu_336 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_2_fu_228 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_30_fu_340 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_31_fu_344 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_20) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_32_fu_348 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_21) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_33_fu_352 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_22) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_34_fu_356 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_23) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_35_fu_360 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_24) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_36_fu_364 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_25) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_37_fu_368 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_26) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_38_fu_372 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_27) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_39_fu_376 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_3_fu_232 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_28) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_40_fu_380 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_29) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_41_fu_384 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_42_fu_388 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_43_fu_392 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_44_fu_396 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_45_fu_400 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_46_fu_404 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_47_fu_408 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_30) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_48_fu_412 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_31) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_49_fu_416 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_4_fu_236 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_32) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_50_fu_420 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_33) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_51_fu_424 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_34) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_52_fu_428 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_35) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_53_fu_432 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_36) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_54_fu_436 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_37) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_55_fu_440 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_38) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_56_fu_444 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_39) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_57_fu_448 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_58_fu_452 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_59_fu_456 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_5_fu_240 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_60_fu_460 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_61_fu_464 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_62_fu_468 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_63_fu_472 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_6_fu_244 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_7_fu_248 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_8_fu_252 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_9_fu_256 <= in_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                inputBuf_fu_220 <= in_stream_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln165_fu_1595_p2 <= std_logic_vector(signed(sext_ln165_fu_1591_p1) + signed(ap_sig_allocacmp_conv_i2_i13_i_load));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_empty_n, ap_predicate_op181_read_state3, out_stream_full_n, icmp_ln172_reg_2120)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((icmp_ln172_reg_2120 = ap_const_lv1_1) and (out_stream_full_n = ap_const_logic_0)) or ((ap_predicate_op181_read_state3 = ap_const_boolean_1) and (in_stream_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_empty_n, ap_predicate_op181_read_state3, out_stream_full_n, icmp_ln172_reg_2120)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((icmp_ln172_reg_2120 = ap_const_lv1_1) and (out_stream_full_n = ap_const_logic_0)) or ((ap_predicate_op181_read_state3 = ap_const_boolean_1) and (in_stream_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_empty_n, ap_predicate_op181_read_state3, out_stream_full_n, icmp_ln172_reg_2120)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((icmp_ln172_reg_2120 = ap_const_lv1_1) and (out_stream_full_n = ap_const_logic_0)) or ((ap_predicate_op181_read_state3 = ap_const_boolean_1) and (in_stream_empty_n = ap_const_logic_0))));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(in_stream_empty_n, ap_predicate_op181_read_state3, out_stream_full_n, icmp_ln172_reg_2120)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (((icmp_ln172_reg_2120 = ap_const_lv1_1) and (out_stream_full_n = ap_const_logic_0)) or ((ap_predicate_op181_read_state3 = ap_const_boolean_1) and (in_stream_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_1271_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln131_fu_750_p2, icmp_ln172_fu_802_p2)
    begin
                ap_condition_1271 <= ((icmp_ln131_fu_750_p2 = ap_const_lv1_0) and (icmp_ln172_fu_802_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_1274_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln131_fu_750_p2, icmp_ln172_fu_802_p2)
    begin
                ap_condition_1274 <= ((icmp_ln131_fu_750_p2 = ap_const_lv1_0) and (icmp_ln172_fu_802_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_1281_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln172_reg_2120, ap_block_pp0_stage0_11001, trunc_ln123_1_reg_2102)
    begin
                ap_condition_1281 <= (not((trunc_ln123_1_reg_2102 = ap_const_lv3_3)) and not((trunc_ln123_1_reg_2102 = ap_const_lv3_2)) and not((trunc_ln123_1_reg_2102 = ap_const_lv3_1)) and not((trunc_ln123_1_reg_2102 = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_1284_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln172_reg_2120, ap_block_pp0_stage0_11001, trunc_ln123_1_reg_2102)
    begin
                ap_condition_1284 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (trunc_ln123_1_reg_2102 = ap_const_lv3_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_1287_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln172_reg_2120, ap_block_pp0_stage0_11001, trunc_ln123_1_reg_2102)
    begin
                ap_condition_1287 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (trunc_ln123_1_reg_2102 = ap_const_lv3_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_1290_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln172_reg_2120, ap_block_pp0_stage0_11001, trunc_ln123_1_reg_2102)
    begin
                ap_condition_1290 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (trunc_ln123_1_reg_2102 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_1293_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln172_reg_2120, ap_block_pp0_stage0_11001, trunc_ln123_1_reg_2102)
    begin
                ap_condition_1293 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (trunc_ln123_1_reg_2102 = ap_const_lv3_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln131_fu_750_p2)
    begin
        if (((icmp_ln131_fu_750_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_inElem_phi_fu_513_p130_assign_proc : process(in_stream_dout, icmp_ln131_reg_2093, icmp_ln134_reg_2107, trunc_ln123_reg_2097, ap_phi_reg_pp0_iter2_inElem_reg_510, inElem_1_fu_1058_p66)
    begin
        if (((icmp_ln134_reg_2107 = ap_const_lv1_0) and (icmp_ln131_reg_2093 = ap_const_lv1_0))) then 
            ap_phi_mux_inElem_phi_fu_513_p130 <= inElem_1_fu_1058_p66;
        elsif ((((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_0)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3E)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_4)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_5)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 
    = ap_const_lv6_6)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_7)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_8)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_9)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_A)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_B)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_C)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_D)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and 
    (trunc_ln123_reg_2097 = ap_const_lv6_E)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_F)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_10)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_11)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_12)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_13)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_14)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_15)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 
    = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_16)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_17)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_18)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_19)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1A)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1B)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1C)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1D)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) 
    and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1E)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_1F)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_20)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_21)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_22)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_23)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_24)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_25)) or ((icmp_ln134_reg_2107 
    = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_26)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_27)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_28)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_29)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2A)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2B)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2C)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2D)) 
    or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2E)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_2F)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_30)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_31)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_32)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_33)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_34)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 
    = ap_const_lv6_35)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_36)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_37)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_38)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_39)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3A)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3B)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3C)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) 
    and (trunc_ln123_reg_2097 = ap_const_lv6_3D)) or ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0) and (trunc_ln123_reg_2097 = ap_const_lv6_3F)))) then 
            ap_phi_mux_inElem_phi_fu_513_p130 <= in_stream_dout;
        else 
            ap_phi_mux_inElem_phi_fu_513_p130 <= ap_phi_reg_pp0_iter2_inElem_reg_510;
        end if; 
    end process;


    ap_phi_mux_outElem_phi_fu_712_p4_assign_proc : process(icmp_ln131_reg_2093, icmp_ln172_reg_2120, ap_phi_reg_pp0_iter2_outElem_reg_709, icmp_ln179_fu_1601_p2)
    begin
        if (((icmp_ln172_reg_2120 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0))) then
            if ((icmp_ln179_fu_1601_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_outElem_phi_fu_712_p4 <= ap_const_lv1_0;
            elsif ((icmp_ln179_fu_1601_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_outElem_phi_fu_712_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_outElem_phi_fu_712_p4 <= ap_phi_reg_pp0_iter2_outElem_reg_709;
            end if;
        else 
            ap_phi_mux_outElem_phi_fu_712_p4 <= ap_phi_reg_pp0_iter2_outElem_reg_709;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_inElem_reg_510 <= "X";
    ap_phi_reg_pp0_iter2_outElem_reg_709 <= "X";

    ap_predicate_op181_read_state3_assign_proc : process(icmp_ln131_reg_2093, icmp_ln134_reg_2107)
    begin
                ap_predicate_op181_read_state3 <= ((icmp_ln134_reg_2107 = ap_const_lv1_1) and (icmp_ln131_reg_2093 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_conv_i2_i13_i_load_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln149_reg_2111, conv_i2_i13_i_fu_480, temp_1_fu_1561_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln149_reg_2111 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_conv_i2_i13_i_load <= temp_1_fu_1561_p2;
        else 
            ap_sig_allocacmp_conv_i2_i13_i_load <= conv_i2_i13_i_fu_480;
        end if; 
    end process;

    fc2_weights_0_address0 <= idxprom4_i_i_fu_785_p1(9 - 1 downto 0);

    fc2_weights_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fc2_weights_0_ce0 <= ap_const_logic_1;
        else 
            fc2_weights_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_756_p2 <= std_logic_vector(unsigned(i_1_fu_216) + unsigned(ap_const_lv9_1));
    icmp_ln131_fu_750_p2 <= "1" when (i_1_fu_216 = ap_const_lv9_140) else "0";
    icmp_ln134_fu_770_p2 <= "1" when (nf_fu_476 = ap_const_lv32_0) else "0";
    icmp_ln149_fu_776_p2 <= "1" when (sf_fu_208 = ap_const_lv32_0) else "0";
    icmp_ln172_fu_802_p2 <= "1" when (sf_3_fu_796_p2 = ap_const_lv32_40) else "0";
    icmp_ln179_fu_1601_p2 <= "1" when (signed(add_ln165_fu_1595_p2) > signed(ap_const_lv16_0)) else "0";
    icmp_ln192_fu_824_p2 <= "1" when (nf_4_fu_818_p2 = ap_const_lv32_5) else "0";
    idxprom4_i_i_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tile_fu_212),64));

    in_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_empty_n, ap_predicate_op181_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op181_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            in_stream_blk_n <= in_stream_empty_n;
        else 
            in_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op181_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op181_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            in_stream_read <= ap_const_logic_1;
        else 
            in_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    nf_4_fu_818_p2 <= std_logic_vector(unsigned(nf_fu_476) + unsigned(ap_const_lv32_1));
    nf_5_fu_830_p3 <= 
        ap_const_lv32_0 when (icmp_ln192_fu_824_p2(0) = '1') else 
        nf_4_fu_818_p2;

    out_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, out_stream_full_n, icmp_ln172_reg_2120, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_stream_blk_n <= out_stream_full_n;
        else 
            out_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_din <= ap_phi_mux_outElem_phi_fu_712_p4;

    out_stream_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln172_reg_2120, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln172_reg_2120 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_stream_write <= ap_const_logic_1;
        else 
            out_stream_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln155_fu_1557_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_fu_1547_p4),16));

        sext_ln165_fu_1591_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_1583_p3),16));

    sf_3_fu_796_p2 <= std_logic_vector(unsigned(sf_fu_208) + unsigned(ap_const_lv32_1));
    temp_1_fu_1561_p2 <= std_logic_vector(unsigned(temp_fu_1532_p7) - unsigned(sext_ln155_fu_1557_p1));
    temp_3_fu_1575_p3 <= 
        fc2_weights_0_q0 when (ap_phi_mux_inElem_phi_fu_513_p130(0) = '1') else 
        ap_const_lv3_0;
    tile_1_fu_790_p2 <= std_logic_vector(unsigned(tile_fu_212) + unsigned(ap_const_lv32_1));
    tile_2_fu_838_p3 <= 
        ap_const_lv32_0 when (icmp_ln192_fu_824_p2(0) = '1') else 
        tile_1_fu_790_p2;
    tmp_1_fu_1583_p3 <= (temp_3_fu_1575_p3 & ap_const_lv8_0);
    trunc_ln123_1_fu_766_p1 <= nf_fu_476(3 - 1 downto 0);
    trunc_ln123_fu_762_p1 <= sf_fu_208(6 - 1 downto 0);
    trunc_ln2_fu_1547_p4 <= temp_fu_1532_p7(14 downto 3);
end behav;
